#+latex_class: article_usual2
# erases make title
# #+BIND: org-export-latex-title-command ""

# fucks all the maketitlestuff just to be sure
#+OPTIONS: num:nil
#+OPTIONS: toc:nil
#+OPTIONS: h:5

#+BEGIN_SRC R :session calc :exports none :results values drawer
dt_nbrs <- fread("/home/johannes/Dropbox/phd/papers/org_pop/tables/tbl_nbrs_v75.csv", quote = "")

dt_nbrs[, .(macro_str = sprintf("#+MACRO: %s %s", nbr_name, nbr_fmt)), grp] %>%
  .[, .(grp_str = paste(macro_str, collapse = "\n")), grp] %>%
  .[, .(grp_str2 = paste0("# ", grp, "\n", grp_str))] %>% 
  .[, paste0(grp_str2, collapse = "\n\n\n")]
  
#+END_SRC

#+RESULTS:
:results:
# pmdb_stats
#+MACRO: nbr_muem_in_pmdb 547
#+MACRO: nbr_opnd_wld 516
#+MACRO: nbr_clsd_wld 101
#+MACRO: nbr_cry_wal1pm_all 64
#+MACRO: nbr_pm_openatm 446


# nbr_pm_regsub
#+MACRO: regsub_cnt_Western_Europe 136
#+MACRO: regsub_cnt_Eastern_Asia 97
#+MACRO: regsub_cnt_Northern_America 77
#+MACRO: regsub_cnt_Southern_Europe 71
#+MACRO: regsub_cnt_Northern_Europe 27


# cbn_info
#+MACRO: nbr_cy_cbn_all 1250
#+MACRO: nbr_cy_cbn_no_cult_spending 2562
#+MACRO: nbr_cy_cbn_no_cult_spending_and_mitr 3393
#+MACRO: nbr_crys_cbn_all 86
#+MACRO: nbr_crys_cbn_no_cult_spending 153
#+MACRO: nbr_crys_cbn_no_cult_spending_and_mitr 164
#+MACRO: nbr_opngs_cbn_all 356
#+MACRO: nbr_opngs_cbn_no_cult_spending 405
#+MACRO: nbr_opngs_cbn_no_cult_spending_and_mitr 407
#+MACRO: prop_opngs_cvrd_cbn_all 0.651
#+MACRO: prop_opngs_cvrd_cbn_no_cult_spending 0.740
#+MACRO: prop_opngs_cvrd_cbn_no_cult_spending_and_mitr 0.744


# opng_rates_fmt
#+MACRO: opng_rate_cbn1 0.0112
#+MACRO: opng_rate_cbn2 0.0061
#+MACRO: opng_rate_cbn3 0.0047


# opng_prop_vlus
#+MACRO: nbr_zero_cbn_all 1 038
#+MACRO: nbr_nzero_cbn_all 212
#+MACRO: prop_nzero_cbn_all 17.0
#+MACRO: nbr_zero_cbn_no_cult_spending 2 307
#+MACRO: nbr_nzero_cbn_no_cult_spending 255
#+MACRO: prop_nzero_cbn_no_cult_spending 10.0
#+MACRO: nbr_zero_cbn_no_cult_spending_and_mitr 3 136
#+MACRO: nbr_nzero_cbn_no_cult_spending_and_mitr 257
#+MACRO: prop_nzero_cbn_no_cult_spending_and_mitr 7.6
#+MACRO: nbr_zero_cbn_controls 5 931
#+MACRO: nbr_nzero_cbn_controls 301
#+MACRO: prop_nzero_cbn_controls 4.8


# popnbrs_p1pm
#+MACRO: nbr_pop_p_1pm_cbn_all 89.2
#+MACRO: nbr_pop_p_1pm_cbn_no_cult_spending 165
#+MACRO: nbr_pop_p_1pm_cbn_no_cult_spending_and_mitr 215
#+MACRO: nbr_pop_p_1pm_cbn_controls 85.0


# cvrgnc
#+MACRO: cvrgd1 79 339
#+MACRO: cvrgd0 1 166
#+MACRO: mdlcnt_ttl 80 505
#+MACRO: cvrgnc_rate 98.6
#+MACRO: nbr_runs_p_cbn_spec 149


# velp_minmax
#+MACRO: velp_cryname_min Hungary
#+MACRO: velp_cryname_max Portugal
#+MACRO: velp_year_scld_min -0.115
#+MACRO: velp_year_scld_max 0.063
#+MACRO: velp_year_pct_min 1.6
#+MACRO: velp_year_pct_max 0.9


# rate_opng_glbl
#+MACRO: rate_opng_glbl_cbn_all 0.00434
#+MACRO: rate_opng_glbl_cbn_no_cult_spending 0.00300
#+MACRO: rate_opng_glbl_cbn_no_cult_spending_and_mitr 0.00283
#+MACRO: rate_opng_glbl_cbn_controls 0.00231


# rate_opng_glbl_yearly
#+MACRO: rate_opng_glbl_yearly_cbn_all 0.00407
#+MACRO: rate_opng_glbl_yearly_cbn_no_cult_spending 0.00289
#+MACRO: rate_opng_glbl_yearly_cbn_no_cult_spending_and_mitr 0.00275
#+MACRO: rate_opng_glbl_yearly_cbn_controls 0.00223


# opng_p1m_glbl_yearly
#+MACRO: opng_p1m_glbl_yearly_cbn_all 246
#+MACRO: opng_p1m_glbl_yearly_cbn_no_cult_spending 346
#+MACRO: opng_p1m_glbl_yearly_cbn_no_cult_spending_and_mitr 364
#+MACRO: opng_p1m_glbl_yearly_cbn_controls 449


# velp_mean
#+MACRO: velp_mean_uscld -0.010
#+MACRO: velp_quantl25_uscld -0.025
#+MACRO: velp_quantl75_uscld 0.007
#+MACRO: velp_mean_scld 0.14
#+MACRO: velp_quantl25_scld 0.35
#+MACRO: velp_quantl75_scld 0.10


# intcpt_info
#+MACRO: intcpt -2.50
#+MACRO: intcpt_exp 0.082


# txinctvs
#+MACRO: txdctblt_cbn3 0.72
#+MACRO: txdctblt_cbn3_exp 2.1
#+MACRO: txdctblt_cbn2 0.48
#+MACRO: tmitr_cbn2 -0.38
#+MACRO: txdctblt_tmitr_interact_cbn2 0.77
#+MACRO: txdctblt_tmitr_interact_cbn2_exp 2.17
#+MACRO: tmitr_1SD_cbn_no_cult_spending 14.1
#+MACRO: tmitr_neteffct_txdctblt1_cbn_no_cult_spending 0.39
#+MACRO: tmitr_neteffct_txdctblt1_cbn_no_cult_spending_exp 1.48
#+MACRO: tmitr_iso3c1 50
#+MACRO: tmitr_iso3c2 36


# smorc_stats
#+MACRO: smorc_lin 0.37
#+MACRO: smorc_lin_flipped -0.37
#+MACRO: smorc_sqrd -0.62
#+MACRO: smorc_top_point_std 0.30
#+MACRO: smorc_top_point 438


# smorc_vlus_2020
#+MACRO: smorc_2020_ITA 362
#+MACRO: smorc_2020_SVK 415
#+MACRO: smorc_2020_ARE 440
#+MACRO: smorc_2020_NZL 463
#+MACRO: smorc_2020_POL 466
#+MACRO: smorc_2020_LVA 467
#+MACRO: smorc_2020_AUS 499
#+MACRO: smorc_2020_ESP 501
#+MACRO: smorc_2020_CAN 513
#+MACRO: smorc_2020_HRV 521
#+MACRO: smorc_2020_CZE 634
#+MACRO: smorc_2020_DEU 660
#+MACRO: smorc_2020_FRA 680
#+MACRO: smorc_2020_BEL 688
#+MACRO: smorc_2020_AUT 694
#+MACRO: smorc_2020_NLD 782
#+MACRO: smorc_2020_FIN 799
#+MACRO: smorc_2020_CHE 806
#+MACRO: smorc_2020_EST 819
#+MACRO: smorc_2020_SWE 859
#+MACRO: smorc_2020_DNK 1 058
#+MACRO: smorc_2020_HUN 1 410
#+MACRO: smorc_2020_NOR 1 544
#+MACRO: smorc_2020_LUX 1 559


# smorc_top_point_stats
#+MACRO: smorctop_below_CYs_cnt 819
#+MACRO: smorctop_above_CYs_cnt 431
#+MACRO: smorctop_below_nbr_opened_cnt 212
#+MACRO: smorctop_above_nbr_opened_cnt 144
#+MACRO: smorctop_below_CYs_prop 65.5
#+MACRO: smorctop_above_CYs_prop 34.5
#+MACRO: smorctop_below_nbr_opened_prop 59.6
#+MACRO: smorctop_above_nbr_opened_prop 40.4


# shweal_stats
#+MACRO: shweal_1SD_cbn_all 7.6
#+MACRO: shweal_iso3c1 50.2
#+MACRO: shweal_iso3c2 57.9
#+MACRO: shweal_lngtd_vlu_year1 64.1
#+MACRO: shweal_lngtd_vlu_year2 71.7
#+MACRO: shweal_cbn_all 0.33
#+MACRO: shweal_cbn_all_exp 1.39
#+MACRO: shweal_lngtd_year1 1991
#+MACRO: shweal_lngtd_year2 2011


# sptinc_stats
#+MACRO: sptinc_1SD_cbn_all 8.9
#+MACRO: sptinc_iso3c1 30.8
#+MACRO: sptinc_iso3c2 39.7
#+MACRO: sptinc_lngtd_vlu_year1 32.5
#+MACRO: sptinc_lngtd_vlu_year2 41.1
#+MACRO: sptinc_cbn_all -0.45
#+MACRO: sptinc_cbn_all_exp 0.64
#+MACRO: sptinc_lngtd_year1 2000
#+MACRO: sptinc_lngtd_year2 2014


# dens_coef_stats
#+MACRO: pm_density_cbn_all 1.20
#+MACRO: pm_density_sqrd_cbn_all -0.29
#+MACRO: pm_density_glbl_cbn_all -0.38
#+MACRO: pm_density_glbl_sqrd_cbn_all -0.28
#+MACRO: dens_cry_top_point_std_cbn_all 2.05
#+MACRO: dens_glbl_top_point_std_cbn_all -0.69
#+MACRO: dens_cry_top_point_cbn_all 0.74
#+MACRO: dens_glbl_top_point_cbn_all 221.05


# dens_cry_top_point_stats
#+MACRO: dens_cry_top_below_CYs_cnt 1 156
#+MACRO: dens_cry_top_above_CYs_cnt 94
#+MACRO: dens_cry_top_below_nbr_opened_cnt 316
#+MACRO: dens_cry_top_above_nbr_opened_cnt 40
#+MACRO: dens_cry_top_below_CYs_prop 92.5
#+MACRO: dens_cry_top_above_CYs_prop 7.5
#+MACRO: dens_cry_top_below_nbr_opened_prop 88.8
#+MACRO: dens_cry_top_above_nbr_opened_prop 11.2


# dens_glbl_top_point_stats
#+MACRO: dens_glbl_top_above_CYs_cnt 844
#+MACRO: dens_glbl_top_below_CYs_cnt 406
#+MACRO: dens_glbl_top_above_nbr_opened_cnt 241
#+MACRO: dens_glbl_top_below_nbr_opened_cnt 115
#+MACRO: dens_glbl_top_above_CYs_prop 67.5
#+MACRO: dens_glbl_top_below_CYs_prop 32.5
#+MACRO: dens_glbl_top_above_nbr_opened_prop 67.7
#+MACRO: dens_glbl_top_below_nbr_opened_prop 32.3


# gdp_stats
#+MACRO: gdp_coef_cbn_no_cult_spending_and_mitr 0.88
#+MACRO: gdp_coef_cbn_no_cult_spending 0.79
#+MACRO: gdp_coef_cbn_all 0.39
#+MACRO: gdp_1SD_cbn_all 24.87
#+MACRO: gdp_1SD_cbn_no_cult_spending 21.33
#+MACRO: gdp_1SD_cbn_no_cult_spending_and_mitr 19.74


# pltcfgs
#+MACRO: ynkplt_cbn_log_likelihoods (eval (concat "#+label: fig:cbn_log_likelihoods\n" "#+caption: model log likelihood distribution per dataset\n" "#+attr_latex: :width 16cm\n" "[[file:figures/plt_v75_cbn_log_likelihoods.pdf]]"))
#+MACRO: ynkplt_cvrgnc (eval (concat "#+label: fig:cvrgnc\n" "#+caption: Model improvement\n" "#+attr_latex: :width 12cm\n" "[[file:figures/plt_v75_cvrgnc.pdf]]"))
#+MACRO: ynkplt_coef_violin (eval (concat "#+label: fig:coef_violin\n" "#+caption: Distribution of coefficient point estimates (Gaussian kernel density estimate; bandwidth = 0.04)\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v75_coef_violin.pdf]]"))
#+MACRO: ynkplt_best_coefs_cloud (eval (concat "#+label: fig:best_coefs_cloud\n" "#+caption: Coefficient point estimate and 95% CI\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v75_best_coefs_cloud.pdf]]"))
#+MACRO: ynkplt_best_coefs_single (eval (concat "#+label: fig:best_coefs_single\n" "#+caption: Model coefficients (best fitting model)\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v75_best_coefs_single.pdf]]"))
#+MACRO: ynkplt_lag_dens (eval (concat "#+label: fig:lag_dens\n" "#+caption: Distribution of lag choice after optimization\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v75_lag_dens.pdf]]"))
#+MACRO: ynkplt_oneout_coefs (eval (concat "#+label: fig:oneout_coefs\n" "#+caption: Model coefficients (best fitting model; colored by significance of model improvement)\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v75_oneout_coefs.pdf]]"))
#+MACRO: ynkplt_oneout_llrt_lldiff (eval (concat "#+label: fig:oneout_llrt_lldiff\n" "#+caption: Model improvement given variable inclusion (Gaussian kernel density estimate; bandwidth = 0.4)\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v75_oneout_llrt_lldiff.pdf]]"))
#+MACRO: ynkplt_oneout_llrt_z (eval (concat "#+label: fig:oneout_llrt_z\n" "#+caption: Distribution of Z-score of log-likelihood ratio test p-value (Gaussian kernel density estimate; bandwidth = 0.1)\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v75_oneout_llrt_z.pdf]]"))
#+MACRO: ynkplt_vrbl_cycnt (eval (concat "#+label: fig:vrbl_cycnt\n" "#+caption: Number of countries with per year per variable\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v75_vrbl_cycnt.pdf]]"))
#+MACRO: ynkplt_cbn_cycnt (eval (concat "#+label: fig:cbn_cycnt\n" "#+caption: Number of countries per year per variable combination\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v75_cbn_cycnt.pdf]]"))
#+MACRO: ynkplt_vif (eval (concat "#+label: fig:vif\n" "#+caption: Distribution of VIF estimates (Gaussian kernel density estimate; bandwidth = 0.1)\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v75_vif.pdf]]"))
#+MACRO: ynkplt_velp (eval (concat "#+label: fig:velp\n" "#+caption: Results of regressing longitudinal variables on year\n" "#+attr_latex: :width 24cm\n" "[[file:figures/plt_v75_velp.pdf]]"))
#+MACRO: ynkplt_oucoefchng (eval (concat "#+label: fig:oucoefchng\n" "#+caption: Coefficient changes given addition of other variables\n" "#+attr_latex: :width 24cm\n" "[[file:figures/plt_v75_oucoefchng.pdf]]"))


# figlbls
#+MACRO: rplt_cbn_log_likelihoods \ref{fig:cbn_log_likelihoods}
#+MACRO: rplt_reg_res_within \ref{fig:reg_res_within}
#+MACRO: rplt_reg_res_all \ref{fig:reg_res_all}
#+MACRO: rplt_best_models_wlag \ref{fig:best_models_wlag}
#+MACRO: rplt_best_models_condensed \ref{fig:best_models_condensed}
#+MACRO: rplt_lag_cprn \ref{fig:lag_cprn}
#+MACRO: rplt_cvrgnc \ref{fig:cvrgnc}
#+MACRO: rplt_coef_violin \ref{fig:coef_violin}
#+MACRO: rplt_best_coefs_cloud \ref{fig:best_coefs_cloud}
#+MACRO: rplt_best_coefs_single \ref{fig:best_coefs_single}
#+MACRO: rplt_lag_dens \ref{fig:lag_dens}
#+MACRO: rplt_oneout_coefs \ref{fig:oneout_coefs}
#+MACRO: rplt_oneout_llrt_lldiff \ref{fig:oneout_llrt_lldiff}
#+MACRO: rplt_oneout_llrt_z \ref{fig:oneout_llrt_z}
#+MACRO: rplt_vrbl_cycnt \ref{fig:vrbl_cycnt}
#+MACRO: rplt_cbn_cycnt \ref{fig:cbn_cycnt}
#+MACRO: rplt_vif \ref{fig:vif}
#+MACRO: rplt_velp \ref{fig:velp}
#+MACRO: rplt_oucoefchng \ref{fig:oucoefchng}
#+MACRO: rplt_oucoefchng_tile \ref{fig:oucoefchng_tile}
#+MACRO: rplt_oucoefchng_cbn1 \ref{fig:oucoefchng_cbn1}
#+MACRO: rplt_oucoefchng_cbn2 \ref{fig:oucoefchng_cbn2}
#+MACRO: rplt_oucoefchng_cbn3 \ref{fig:oucoefchng_cbn3}


# tbllbls
#+MACRO: rtbl_regrslts_wcptblF \ref{tbl:regrslts_wcptblF}
#+MACRO: rtbl_regrslts_wcptblT \ref{tbl:regrslts_wcptblT}
#+MACRO: rtbl_descs \ref{tbl:descs}
#+MACRO: rtbl_cbn_cpsgn \ref{tbl:cbn_cpsgn}
:end:



 
* Appendix


# #+label: fig:openings
# #+caption: Private Museum openings (absolute and population-rate) of 12 countries with highest counts. 
# [[file:figures/foundings_country_cnt_and_rate.pdf]]

# #+label: fig:cpltns_vrbl_plot_v2
# #+caption: Number of countries with data per year
# [[file:figures/cpltns_vrbl_plot_v2.pdf]]



{{{ynkplt_vrbl_cycnt}}}



# grok out the format for inserting figure label/caption/dimension macros

# #+macro: plt_cbn_cycnt_insrt_r (eval (concat "#+caption: Number of countries per year per variable combination\n" "#+label: plt_v75_cbn_cycnt\n" "#+attr_latex: :width 4cm\n" "[[file:figures/plt_v75_cbn_cycnt.pdf]]"))

# {{{plt_cbn_cycnt_insrt_r}}}


{{{ynkplt_cbn_cycnt}}}




Figure {{{rplt_vrbl_cycnt}}} shows the country-year coverage of the main variables (other HNWI thresholds and inequality shares follow the ones depicted).
#
In particular it can be seen that the coverage of wealth variables in the WID improves substantially from 1995 onwards, a pattern that is to a lesser extent also visible in indicators of cultural spending and top marginal income tax rates.
#
Given this state of data coverage and the fact that five years of subsequent data are required for lag length optimization, the observation period for the largest proportion of countries starts in the year 2000 or later  (figure {{{rplt_cbn_cycnt}}}, the start 1995 is set by the availability of Artnews collector ranking data from 1990 onwards).
#



# #+label: fig:world_plot_faceted
# #+caption: Countries colored by number of country-years per combination
# [[file:figures/world_plot_faceted_v2.pdf]]


# Figures [[fig:world_plot_faceted]] and [[fig:cbn_cnt_line_plot]] illustrate the variation of country-year coverage between the variable combinations. 

# As a consequence of the data availability of longitudinal variables, for most countries the analysis covers the years 2000-2020.


** Data processing

*** Cultural spending

This combination of multiple data sources requires the harmonization of different reporting standards: 
#
Whereas the the IMF and Eurostat report data exclusively as "Total government expenditure" (TLYCG), the UN uses "Final consumption expenditure" (P3CG); the OECD reports data in both formats ("Total government expenditure" is calculated from "Final consumption expenditure" as well as a number of other items, such as compensation of employees and subsidies). 
#
Moreoever, within each format minor variations exist between data sources, the data for a country-year is thus chosen in order of OECD followed by UN for P3CG, and OECD followed by IMF followed by Eurostat for TLYCG.
# (for the UN data, sometimes data is also reported in multiple Series corresponding to different SNA methodologies (see [[textcite:&UN_2022_consumption]] footnote 2 for details); here SNA 2008 methodology is chosen if available, otherwise the mean of the other series is taken).


As the overall goal is to create a complete picture of government expenditure, Total government expenditure is estimated from Final consumption expenditure for country-years where data is only available for the latter.
# based on the years in which the series overlap
For countries where TLYCG and P3CG series have some overlap and years exist with P3CG data but not TLYCG data, a country-specific scaler to convert P3CG to TLYCG is constructed from overlapping years, which is then used to impute TLYCG for the years in which only P3CG data is available.
#
For countries with only P3CG data, the average ratio of all country-years with both P3CG and TLYCG data is chosen to impute TLYCG (as on average P3CG is 58% of TLYCG, the average scaler is 1/0.58 = 1.72). 
#
Amounts are reported in current local currency units and converted to 2021 USD using price indices and purchasing power parity adjusted exchange rates from the World Inequality Database (WID,  [[citeyear:&WID_2021_WID]]).
#
I estimate coefficients of the cultural spending variable as well as its squared term to account for potential non-linearities similar to those present in the density dependence paradigm ([[cite:&Hannan_1992_dynamics]];  elaborated in section Control Variables); in particular, the crowding-out argument appears to indicate competition, while the crowding-in argument bears similarities to legitimation. 

# [fn::An alternative would be to use purchasing power parity exchange rates, which reflect local price levels (as [[textcite:&Blanchet_2017_conversions]] argues, 1 euro or 7 yuan allow the purchase of the same amount of oil on international markets, but different amounts of food in Beijing or Paris). As the art market is however substantially transnational [[parencite:&Velthuis_Curioni_2015_canvases]], and discussion of government spending heavily revolves around acquisition budgets (which are dedicated to the purchase of artworks that often are  international), I consider market exchange rates more appropriate.]





** Combination composition

#+INCLUDE: "./tables/tbl:cbn_cpsgn.tex" export latex


Table {{{rtbl_cbn_cpsgn}}} shows the coverage of datasets by region. 
#
Relative between-dataset differences are particularly strong for Africa, Latin America and Europe.
#
While Europe with *more than half of the country-years* is "DS all IVs" constitutes the largest region (indicating that European countries report relatively detailed statistics on government spending), its share declines to *XX%* and *YY%* in "DS -CuSp" and "DS -CuSp/TMITR", respectively.
#
Conversely, Africa and Latin America claim larger shares in the larger datasets, with the former becoming the region contributing the largest nubmer of country years (*X* or *Y%*) in "DS -CuSp/TMITR".
#
The proportion of North America and Oceania also declines in larger datasets, but this results in comparatively less changes in dataset composition as these regions consist of relatively few countries. 



with the shares of the former increasing with dataset size in country-years (*list percentages here*, while she latter 



** coef distribution

# #+label: fig:coef_violin
# #+caption: Coefficient point estimate distribution (variation based on different variable choices)
# [[file:figures/plt_v75_coef_violin.pdf]]

{{{ynkplt_coef_violin}}}



** model improvement given inclusion of variables 
:PROPERTIES:
:ID:       ddb30663-9a58-4af5-977c-43f83903776c
:END:

# #+label: fig:oneout_llrt_lldiff
# #+caption: Model fit difference given variable inclusion
# [[file:figures/plt_v75_oneout_llrt_lldiff.pdf]]

{{{ynkplt_oneout_llrt_lldiff}}}


# #+label: fig:oneout_llrt_lldiff
# #+caption: Significance of model improvement given variable inclusion
# [[file:figures/plt_v75_oneout_llrt_z.pdf]]

{{{ynkplt_oneout_llrt_z}}}

To investigate whether a variable improves the model, a comparison is made between the full model and the full model without the variable in question.
# 
For each dataset there are 36 models (due to variables choices for HWNI (4 different thresholds) and inequality measures (1 of 3 for both wealth and income inequality)), resulting in 108 models in total. 
#
For each variable in each of these models a reduced model is constructed by removing the variable in question and comparing model fit to the full model.
#
# fuck actually doesn't really make sense to compare a full model with smorc_linear and squared to one iwth only linear
# also my improvement of smorc is weird: same for both smorc linear and smorc squared
#
If a variable had a squared term or interaction, it was removed together with the main term.
#
Furthermore additional reduced models were constructed, namely one without the four density variables (country and global density linear and squared), as well as one without the density variables and closings.
#
Given that the datasets differ in their number of variables, a different number of reduced models is calculated per dataset, in particular *684* for "DS all IVs", *612* for "DS --CuSp", and *540* for "DS --CuSp/TMITR". 
# 
The lags of the reduced models were not optimized due to computational limitations. 



Figure {{{rplt_oneout_llrt_lldiff}}} shows the distribution of differences in log-likelihood between the full and reduced models per variable and dataset.
#
Furthermore, a likelihood ratio test ($LR = 2[LL_{reduced} - LL_{full}]$) was conducted to compare each reduced to its corresponding full model.
#
The likelihood ratio statistic follows a Chi-square distribution; its corresponding p-value was converted to a z-score to facilitate interpretation.
#
The distribution of z-scores per variable and dataset is shown in figure {{{rplt_oneout_llrt_z}}}.


Both analysis correspond in large parts to the results of the main regression analysis *table X* insofar as variables with significant coefficient correspond to significant and/or substantial model improvements.
#
There are however a few exceptions, such as tax deductibility of donations in "DS -CuSp/TMITR", GDP per capita in "DS all IVs" as well as some  wealth inequality variables in "DS all IVs" in which a significant coefficient does not always correspond to a significant model improvement. 



** Mediation: unsure if to use at all 

#+latex: \begin{landscape}

{{{ynkplt_oucoefchng}}}

#+latex: \end{landscape}

I furthermore analyze the coefficients of the restricted models to investigate potential mediation; results are presented in figure {{{rplt_oucoefchng}}}.
#
The variables (or variable sets of all density variables and all density variables plus closures) that are added are placed on the x-axis, the coefficients of the full model are placed on the y-axis;
# 
Each point shows the average difference between the coefficient of the full and the restricted model and can be understood as the effect that adding variable v_x to the model has on the coefficient of variable v_y.
#
For example, if GDP has a coefficient of 0.3 in the full model and one of 0.1 in the restricted model (e.g. one without cultural spending), the difference is 0.3 - 0.1 = 0.2; thus adding cultural spending to the model results in an increase of the GDP coefficient by 0.2. 
#
Positive coefficient changes (i.e. a larger coefficients in the full model than in the restricted model) are colored as red, negative coefficient changes as blue; points are furthermore scaled by the absolute coefficient size to compare both positive and negative changes. 


A number of findings can be gleaned from this analysis.
#
Firstly, wealth and income inequality appear "mutually reinforcing".
#
The inclusion of income inequality increases the coefficients of wealth inequality (which is positive in the full model) and the inclusion of wealth inequality decreases further the negative coefficient of income inequality (which in the full model is negative).
#
This unexpected pattern (as well as the divergent inequality in general) clearly calls for further research to disentangle relations of inequality.


Secondly, a number of variables appear to partly mediate GDP.
#
The coefficient of GDP decreases as other variables are added, which indicates that part of the effect is mediated through these variables.
#
This in particular concerns the effects of density, tax incentives and cultural spending, and to a lesser extent the effect of inequalities (for "DS --CuSp" and "DS --CuSp/TMITR") and some HNWI measures (for "DS all IVs").
#
Conversly, adding GDP to a model in which it was not included before reduces the coefficients of HNWIs, museums of modern/contemporary art and country-level density for "DS --CuSp" and "DS --CuSp/TMITR". 
#

does it need to be mediation? could be any kind of covariance? 






** lag choice
:PROPERTIES:
:ID:       68b9f836-26ed-4340-899f-4d6c31192cd5
:END:

# #+label: fig:lag_dens
# #+caption: Distribution of lags of longitudinal variables
# [[file:figures/plt_v75_lag_dens.pdf]]

{{{ynkplt_lag_dens}}}

Figure {{{rplt_lag_dens}}} shows the distribution of the lag of the coefficient after optimization.
#
As often time lags different from one year are chosen (which would likely constitute the default if they were not varied), it can be seen that allowing the lag to vary substantially increases model fit. 
#
It furthermore seem to be the case that the HNWI coefficients (which are not significant) vary the most in regards to their lag choice (which is plausible since a non-substantial overall effect could imply that the particular lag does not matter much). 
# , which is plausible insofar as a flat 




** Multicollinearity 

{{{ynkplt_vif}}}


VIFs were calculated for the best-fitting model of each variable set and dataset (108 models in total given 1 of 4 HWNI variables \times 1 of 3 income inequality variables \times 1 of 3 wealth inequality variables \times 1 of 3 datasets) using the R =performance= package [[parencite:&Luedecke_etal_2021_performance]]. 
# 
As squared variables and interactions can result in high VIFs without substantial collinearity, I calculate VIFs once for the full model and once after excluding squared variables and interactions.
# 
Figure {{{rplt_vif}}} shows the distribution of the variance inflation factors.
#
While VIFs can be substantial when including squared variables and interactions, no multicollinearity issues are present when focusing only on the linear variables (all VIFs < 10, all VIFs except global density (which after removing squared variables is still based on the same data as global density) < 5).
#



** Longitudinal development

#+latex: \begin{landscape}

{{{ynkplt_velp}}}

#+latex: \end{landscape}

Next to these overall statistics, the within-country changes were analyzed to characterize the development of the longitudinal variables over the observation period.
#
In particular, for each variable a separate regression model was run which regresses the variable in question at lag 0 against year while allowing slopes and intercepts to vary by country (year was 0 in 1995, the beginning of the observation period).
#
*can only cover linear country trends, especially since changes are usually reported as percentage change*
#
Results are presented in figure {{{rplt_velp}}}.
#
The histogram shows the distribution of country slopes, while the dot and whiskper shows the overall slope estimate with a 95% confidence interval.
#
For example the overall slope of top marginal income tax rates is {{{velp_mean_uscld}}} (indicating an average yearly decrease of top marginal income tax rates by {{{velp_mean_scld}}} percentage points), however the histogram shows that countries can substantially diverge from this overall slope: 
#
Slopes of countries (with at least 20 years of data) can range from a minimum of {{{velp_year_scld_min}}} (a yearly decrease by {{{velp_year_pct_min}}} percentage points in the case of {{{velp_cryname_min}}}) to a maximum of {{{velp_year_scld_max}}} (a yearly increase of {{{velp_year_pct_max}}} percentage points in the case of {{{velp_cryname_max}}}), with 25% and 75% slope quantiles corresponding to {{{velp_quantl25_uscld}}} (-{{{velp_quantl25_scld}}}%) and {{{velp_quantl75_uscld}}} ({{{velp_quantl75_scld}}}%), respectively.
#
Furthermore, the correlation between slope and intercept is included:
#
A positive correlation indicates that countries with higher constants (i.e. predicted value in 1995) achieve higher growth over the observation period than countries with lower constants (thereby "extending their lead"), whereas negative correlations indicate that countries with lower constants experience higher growth (thereby "catching up").


main findings:
- to the extent to which histograms of same variable are different between combinations, countries are not missing at random -> less biased estimates
- TI decrease
- smorc increase
- inequalities show much variation, depending on dataset
- hwni increase, but very unequally, many 0s
  not artifact of construction: many 0 slopes also for low thresholds where there are almost no zeroes
  
  





