#+latex_class: article_usual2
# erases make title
# #+BIND: org-export-latex-title-command ""

# fucks all the maketitlestuff just to be sure
#+OPTIONS: num:nil
#+OPTIONS: toc:nil
#+OPTIONS: h:5


 
* Appendix


#+label: fig:openings
#+caption: Private Museum openings (absolute and population-rate) of 12 countries with highest counts. 
[[file:figures/foundings_country_cnt_and_rate.pdf]]

# #+label: fig:cpltns_vrbl_plot_v2
# #+caption: Number of countries with data per year
# [[file:figures/cpltns_vrbl_plot_v2.pdf]]

# As figure [[fig:cpltns_vrbl_plot_v2]] shows,

#+label: fig:vrbl_cycnt
#+caption: Number of countries with data per year
file:figures/plt_v75_vrbl_cycnt.pdf

Figure [[fig:vrbl_cycnt]] shows the country-year coverage of the main variables (other HNWI thresholds and inequality shares follow the ones depicted).
#
In particular it can be seen that the coverage of wealth variables in the WID improves substantially from 1995 onwards, a pattern that is to a lesser extent also visible in indicators of cultural spending and top marginal income tax rates.
#
Given this state of data coverage and the fact that five years of subsequent data are required for lag length optimization, the observation period for the largest proportion of countries starts in the year 2000 or later (*figure XXX*). 





# #+label: fig:world_plot_faceted
# #+caption: Countries colored by number of country-years per combination
# [[file:figures/world_plot_faceted_v2.pdf]]

#+label: fig:cbn_cnt_line_plot
#+caption: Number of countries per year per variable combination
[[file:figures/cbn_cnt_line_plot_v2.pdf]]

Figures [[fig:world_plot_faceted]] and [[fig:cbn_cnt_line_plot]] illustrate the variation of country-year coverage between the variable combinations. 

As a consequence of the data availability of longitudinal variables, for most countries the analysis covers the years 2000-2020.

** Combination Composition

#+INCLUDE: "./tables/tbl:cbn_cpsgn.tex" export latex

Table \ref{tbl:cbn_cpsgn} shows the coverage of datasets by region.
#
Relative between-dataset differences are particularly strong for Africa, Latin America and Europe.
#
While Europe with *more than half of the country-years* is "DS all IVs" constitutes the largest region (indicating that European countries report relatively detailed statistics on government spending), its share declines to *XX%* and *YY%* in "DS -CuSp" and "DS -CuSp/TMITR", respectively.
#
Conversely, Africa and Latin America claim larger shares in the larger datasets, with the former becoming the region contributing the largest nubmer of country years (*X* or *Y%*) in "DS -CuSp/TMITR".
#
The proportion of North America and Oceania also declines in larger datasets, but this results in comparatively less changes in dataset composition as these regions consist of relatively few countries. 



with the shares of the former increasing with dataset size in country-years (*list percentages here*, while she latter 



** coef distribution

#+label: fig:coef_violin
#+caption: Coefficient point estimate distribution (variation based on different variable choices)
[[file:figures/plt_v75_coef_violin.pdf]]




** model improvement given inclusion of variables 
:PROPERTIES:
:ID:       ddb30663-9a58-4af5-977c-43f83903776c
:END:

#+label: fig:oneout_llrt_lldiff
#+caption: Model fit difference given variable inclusion
[[file:figures/plt_v75_oneout_llrt_lldiff.pdf]]

#+label: fig:oneout_llrt_lldiff
#+caption: Significance of model improvement given variable inclusion
[[file:figures/plt_v75_oneout_llrt_z.pdf]]


** lag choice
:PROPERTIES:
:ID:       68b9f836-26ed-4340-899f-4d6c31192cd5
:END:
#+label: fig:lag_dens
#+caption: Distribution of lags of longitudinal variables
[[file:figures/plt_v75_lag_dens.pdf]]
