#+latex_class: article_usual2
# erases make title
# #+BIND: org-export-latex-title-command ""

# fucks all the maketitlestuff just to be sure
#+OPTIONS: num:nil
#+OPTIONS: toc:nil
#+OPTIONS: h:5

# -*- org-export-babel-evaluate: nil -*-

* Investigating causes of private museum founding

** Introduction


Private museums constitute a substantial development in the cultural sector in the last decades.
#
While museums have been privately founded throughout history, recent decades have seen an increase in their founding that has been coined the "private museum boom" [[parencite:&Walker_2019_collector]], which has resulted in hundreds of private museums being founded since 2000 [[parencite:&LarrysList_2015_report]].
#
These institutions raise questions about the configuration of the art field in particular, and the development of new organizational forms in general:
#
Is their emergence related to a decline of public institutions which shifts decision-making further into the hands of wealthy, private individuals, who use the image of public benefit to legitimate increasing inequalities?
#
Are private museums a short-lived fad, or will they leave a lasting impact in the art field, potentially wrangling consecrating power from other museums?
#
While no single study can address all these questions simultaneously, I argue that an analysis of the foundings of private museum constitutes a sofar unexploited opportunity to shed light onto larger questions of organization form development and power arrangements. 

 
Multiple hypotheses for the spread of this new form have been raised, but systematic analyses of these have been lacking.
# 
In particular, the rise of private museums has been hypothesized to be associated to tax incentives, reductions in government spending, increasing inequality and increasing elite wealth.


Combining various socio-economic and art field data sources, I conduct a quantitative test of these hypotheses of datasets of 1258, 2574 and 3400 country years using random effects negative binomial regression models.
#
While I find moderate support for a role of tax incentives, government spending is found to be associated primarily positively (not, as hypothesized, negatively) with private museum founding.
#
Furthermore the effects of inequality are divergent, as a positive association with private museum founding is found for wealth inequality and a negative one for income inequality.
#
Finally, elite wealth effects are primarily negative (some although are positive) as well as small.


** Delineating private museums
Effectively defining private museums is not a straightforward task, and depends on the conceptualization of the terms "private" and "museum", neither of which are unambiguous concepts either.
#
For this study I use "private" to denote being established by a private art collector, art collector couple, or their descendants; such a focus on the individual founder thus does not include museums operated by companies (what may more generally be called the "private sector") or groups of people.
#
A "museum" is conceptualized as an organization that possesses a building and a collection of its own (which excludes kunsthalles and exhibition centers), which is sufficiently accessible to the public.
#
For the purpose of this research I also only include such institutions that focuses on modern or contemporary art, with modern and contemporary art operationalized as art created after 1900.

** Theoretical background

*** Tax incentives

Tax incentives have been investigated as a factor for influencing various kinds of charitable or philanthropic behavior and private museum founding in particular.
#
Tax incentives decrease the net cost of charitable activities, and can thus expected to be shaping philanthropic behavior to the extent to which actors are not purely motivated by altruistic intentions.
#
While themes of disinterestedness and intrinsic passion are strongly present in the self-presentations of founders [[parencite:&BMW_2016_hall;&BMW_2016_salsali;&Bechtler_Imhof_2018_future;&Duron_2020_rebaudengo]], they might be more strategic framings to adhere to art market norms [[parencite:&Velthuis_2007_talking]] than real motivations guiding actual behavior.

textcite:&Walker_2019_collector qualitatively investigates the legal frameworks and tax exemptions that private museums receive in a number of regions, and concluded that "the formation of many private museums in the last two decades are directly or indirectly linked to generous tax incentives as they help to offset individual tax burdens and promote arts philanthropy. [...] The generosity and breadth of American, Australian, English and European tax law is a factor in the promotion of private museums" (p.37).

#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 1*: Tax incentives are associated with higher rates of private museum founding.


*** State funding

Another argument for the emergence of private museums has been the decline or absence of state support for the arts, particularly the acquisition budgets for public museums, either in absolute terms or relatively to the (ostensibly strongly increasing) prices for contemporary art [[parencite:&Bechtler_Imhof_2018_future;&Walker_2019_collector;&Song_2008_private;&StylianouLambert_etal_2014_museums;&Zorloni_Resch_2016_opportunities;&Gnyp_2015_collectors;&Clarke_1991_UK;&Brown_2019_private;&Franklin_Papastergiadis_2017_anti;&Quemin_2020_power]].
#
On the contrary, the acquisition budgets of private museums are characterized as much less restricted, enabling them to outbid their public counterparts [[parencite:&Durand_2018_jumex;&Bechtler_Imhof_2018_future;&Gnyp_2015_collectors]].
# 
Thus as public museums constitute less attractive partners for private collectors for loaning, storing, and buying their collections; it is argued that private collectors are in turn incentivized to establish their own institutions.


Such theorized substitute relations between state and private funding are more generally referred to as "crowding-out" in philanthropic studies (cf. [[cite:&Bekkers_Wiepking_2010_literature]]).
#
While the term "crowding-out" originated in response to the question of how charitable behavior would change if states were to /increase/ funding, the underlying theoretical mechanism is the same in the case of explaining private museum founding with decline in government expenditure:
#
In both cases, donors are motivated (for altruistic or other reasons) to provide of public goods, and thus allocate their donations in response to the funding choices of the government.
#
However, [[textcite:&DeWit_etal_2018_philanthropy]] and [[textcite:&Lena_2019_entitled]] argue that government funding could also signal valuation of an activity, which raises the possibility of a positive association between government funding and private museum founding.

#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 2a*: Higher government cultural spending is associated with lower rates of private museum founding.

#+latex: \noindent
*Hypothesis 2b*: Higher government cultural spending is associated with higher rates of private museum founding.


*** Inequality
Critical Philanthropy Studies have argued for links between philanthropy more generally and distributional issues: 
#
[[textcite:&Maclean_etal_2021_philanthropy]] argue that "the ultimate purpose of elite philanthropy [...] is to legitimate and make palatable the extreme inequalities generated by the forward march of global capitalism" (p.14).
#
A similar arguments are made by [[textcite:&Glucksberg_RussellPrywata_2020_philanthropy]], who compare the philanthropic donations of the most charitable givers to their business activities and argue, after finding the former to be dwarfed by the latter, that "philanthropy plays a role in helping elites legitimize their own wealth, and thus in legitimizing inequality" (p.2).
#
Furthermore, [[textcite:&Giridharadas_2018_winners]] argues that inequality causes dissatisfaction, leading philanthropists to engage in philanthropy "out of a mix of altruism and the self-preservational desire to cool public anger" (p.172).


#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 3*: Higher income and/or wealth inequality is associated with higher rates of private museum founding.

*** Elite Wealth

The founding of private museums has been associated with the rise of (Very or Ultra) High Net Worth Individuals (HNWI, VHNWI, UHNWI; corresponding to a wealth of 1 million, 5 million and 30 million USD respectively) [[parencite:&Walker_2019_collector p.15/39]] as these "spaces generate costs and mostly no incomes" (cite:&Gnyp_2015_collectors p.236, cite:&Zorloni_Resch_2016_opportunities p.16), and hence are only feasible to maintain by individuals with substantial disposable funds (also cf. [[cite:&Reckhow_2020_politics]]).

#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 4*: Higher numbers of (V/U)HNWIs are associated with higher rates of private museum founding.

** Data

The unit of analysis constitutes a country-year.
#
Ideally individual-level data would be used to construct collector-year as the unit of analysis, which would allow detailed investigation into collector decision-making (it would e.g. allow to include collector-level variables in the comparison of which collectors found or do not found museums).
#
However, no such databases exist of the art collector population, in particular regarding its longitudinal development, to make such an analysis feasible.
# 
Therefore the more aggregate unit country-years is used as the unit of analysis, which results in a panel data analysis (unbalanced to the extent that variable coverage differs between country-years).

*** Dependent Variable: Number of private museum foundings per country-year
To document the development of private museums, existing databases of private contemporary art museums parencite:LarrysList_2015_report,Independent_collectors,global_private_museum_network_2020_museums,BMW_Independent_Collectors_2018_artguide,vdEerenbeemt_vdWauw_DDD_2016 have been combined.
#
Additionally, web research has been conducted by searching in a number of online art media[fn::The media sources used were: Artforum, Artnet, Art Territory, Artsy, My Art Guides, Artnews, Artfcity, Frieze, The Art Wolf, The Art Newspaper, Art Privee, Widewalls, White Hot Magazine and Hyperallergic.] for the term "private museum", "private art museum" and "private contemporary art museum".
#
After recording the names and deleting duplicates, it was investigated using publicly available information whether the organization corresponds to the employed definition of a private museum.
#
Following this, additional information about each museum was collected by student assistants, the most relevant for this research being country and opening year.
#
Currently, the database includes 548 museums located in 63 countries, with the majority being located in Western Europe (148), East Asia (96) and North America (84).
#
Information on country and opening year is used to construct a count indicator of the number of private museums opened in each country-year.

*** Independent Variables
**** Tax incentives

The report "Rules to Give - A Global Philanthropy Legal Environment Index" [[parencite:&Quick_Kruse_Pickering_2014_philanthropy]] is used to construct a time-invariant (as no longitudinal data sources were available) measure of tax incentives.
#
I use the binary indicators whether non-profits are exempt from at least some taxes, and whether individuals can receive tax deductions for donations to non-profits.

Top marginal income tax rate data is taken from the Index of Economic Freedom of the World parencite:&Fraser_2022_economic_freedom, of which it constitutes a sub-item.
# 
As top marginal income tax rates are only expected to provide an incentive if tax donations are tax-deductible, I calculate an interaction term between the tax-deductibility of donations and marginal income tax rates (as tax deductibility is a binary variable, the value of the interaction term is 0 for countries in which charitable donations are not tax-deductible, and the value of top marginal income tax rates otherwise).

*** Cultural Spending
I use data on government spending on culture, recreation and religion collected by the UN [[parencite:&UN_2022_consumption]], the IMF [[parencite:&IMF_2022_GFS]], the OECD [[parencite:&OECD_2022_SNA_TABLE11_ARCHIVE;&OECD_2022_SNA_TABLE11]] and Eurostat [[parencite:&Eurostat_2022_COFOG]] as an indicator of cultural spending.
#
As the amounts reported are in current local currency units, they are converted to 2021 US dollar using price indices and market exchange rates from the World Inequality Database [[citeyear:&WID_2021_WID]].

*** High Net Worth Individuals
I also use the Wealth Inequality Database (WID, [[citeyear:&WID_2021_WID]]) to calculate the first the percentage, and then the number of High Net Worth Individuals (HNWI), i.e. the population proportion above a certain wealth threshold in a given year.
#
The WID contains for each country-year measures of the wealth at various quantile thresholds, i.e. the value for the 90th percentile describes the amount of wealth of the least wealthy member of the top 10%.
#
I use these thresholds to calculate the percentage of people above a certain threshold (I use thresholds of 1 million, 5 million, 30 million, 200 million USD) by linearly interpolating between the two nearest percentiles above and below the respective threshold.
#
The so-obtained proportion of HNWIs is converted into a count using population size from World Bank data.


*** Inequality
#
The WID also provides gini coefficients for wealth and pre-tax income[fn::while post-tax income is also included, its coverage is very limited]. The top 1% and 10% wealth and income shares (previously used to construct the number of HNWIs) are also used as alternative measures of inequality, as these measures are commonly used in in WID publications.



*** Control Variables
**** GDP per capita and Population size
Wealthier nations likely have larger population shares interested in art consumption, thus increasing the prestige private museum founders anticipate when making the choice whether to found a private museum.
#
Population size is included as an offset (see section [[id:d2d676fc-e644-4815-a06d-906a30c823f0][Analysis]]).

**** Artnews collectors
As private museums are founded by collectors, they are more likely to be founded in countries and times where many potential founders exist.
#
I thus construct an indicator of the population of art collectors from the Artnews magazine collector ranking, a index published yearly since 1992 of the 200 art collectors the magazine considers most important, prestigious and/or influential.


**** Density dependence
Research on organizational population parencite:&Carroll_1989_density;&Hannan_1992_dynamics has argued that foundings of organization are driven by legitimacy and competition, which are measured by indicators describing the organizational population. 
#
I therefore add a linear term (which measures legitimacy) and a squared term (which measures competition).
#
Given to the transnational nature of the art field (due which legitimation and competition might not be limited to country borders) I also add global linear and squared density measures which are the same for every country in a given year and describe the number of museums open worldwide in a given year.
#
I also control for a potential delegitimating effect of private museum closures (71 private museums have closed so far); due to the unequal distribution of these closures I for now only add a global count.

**** Museum population
Private museums can interact with other museums: they can draw legitimacy from them or compete with them (resulting in a dynamic similar to the one of density-dependece).
#
To control for these potential influences, I use the Museums of the World database [[parencite:&deGruyter_2021_MOW]] to describe a country's art museum population; due to data issues I construct a time-invariant indicators of the number of modern and contemporary art museums having opened until 1990.



** Analytical strategy

*** Variable combinations
Despite substantial efforts to collect complete data for the relevant variables, it was not possible to collect data for all country-years.
#
I therefore construct three datasets, one dataset with all variables (1258 country years, 86 countries; referred to as "DS all IVs"), one with all variables except cultural spending (2574 country years, 153 countries; "DS --CuSp"), and one with all variables except cultural spending and marginal income tax rates (3400 country years, 163 countries; "DS --CuSp/TMITR").

*** Variable selection
As concrete operationalizations of variables have been absent, multiple regression models are run varying only the variable measuring the concept in question: For the number of HNWIs, thresholds of 1, 5, 30, 200 million USD and for wealth and income inequality the 10% share, the 1% share the and gini coefficient.
#
This choices result in 36 possible variable combinations (4 HNWI variables \times 3 income inequality variables \times 3 wealth inequality variables). 

*** Time lags
As the literature has not yet investigated the time different mechanisms need to create effects, I exploratory vary the time lag of each longitudinal variable between one and five years, and select the best-fitting one (with highest log-likelihood).
#
95 320 models are run, of which all converge successfully. 


*** Regression specification
Each regression model is specified as a negative binomial model (which is robust to potential overdispersion of the dependent variable) model is run using the xtnbreg command of Stata 14.
#
Random country intercepts are added to account for clustering of observations in countries.
#
I furthermore use population as an offset (which estimates founding rate per capita) to allow comparison between countries of different population sizes; all count predictors are therefore first transformed into per capita rates.
#
To facilitate convergence and interpretation, all variables except the binary variables of tax exemptions for non-profits and tax deductibility of charitable donations are also rescaled to a mean of 0 and a standard deviation of 1.

# #+latex: \begin{landscape}
# #+latex: \input{./tables/summary_stats.tex}
# #+latex: \end{landscape}

** Results
#+label: plt_v62_coef_violin
#+caption: distribution of main coefficients
#+attr_latex: :width 18cm
[[file:figures/plt_v62_coef_violin.pdf]]


Coefficients are to be interpreted as logged multipliers of a country's private museum founding rate, therefore a coefficient of 0.2 corresponds to a exp(0.25) = 1.28 multiplier, i.e. a 28% increase in average country founding rate given a 1 standard deviation change in the independent variable.
#
Figure [[plt_v62_coef_violin]] shows the distribution of the main coefficients of the best fitting model of the 36 variable selections.

The results for tax incentives (H1) support the literature, as tax deductibility of donations is positively associated with private museum founding in all datasets.


Government cultural spending is found to have a positive association with private museum founding.
# 
This finding thus does not support the crowding-out argument of the private museum literature of private museum founding as a consequence of declining government spending (H2a).

For the inequality variables (H3), results are mixed:
#
While income inequality is associated with lower founding, wealth inequality variables are positively associated with the establishment of new private museums.

Finally, the effect of HNWIs (H4) is mostly negative and relatively small in the two larger datasets, but differs between positive and negative (without a clear pattern) depending on the HNWI threshold in the smallest dataset.

** Discussion and conclusion

This exploratory analysis gives insights to interpret the emergence of private museums.
#
While they seem to some extend supported by tax incentives, they so far do not seem to be indicative of a wider expansion of private elite influence as their openings follow state expenditure (rather than filling in gaps left by decreasing cultural spending).
#
Similarly, they are only weakly associated with increases of the HNWI population and show divergent relations to inequality.


The divergent effect of wealth and income inequality calls for both further theoretical consideration and empirical analysis. 

* References
# \hypertarget{refs}{}

#+Latex: \begin{sloppypar}
#+Latex: \printbibliography
#+Latex: \end{sloppypar}



