#+latex_class: article_egos
# erases make title
# #+BIND: org-export-latex-title-command ""

# fucks all the maketitlestuff just to be sure
#+OPTIONS: num:nil
#+OPTIONS: toc:nil
#+OPTIONS: h:5

# -*- org-export-babel-evaluate: nil -*-

* investigating private museum founding
Johannes Aengenheyster

#+latex: \noindent
Phd student at University of Amsterdam

#+latex: \noindent
j.aengenheyster@uva.nl


** Introduction

Private museums constitute a substantial development in the cultural sector in the last decades.
#
While museums have been privately operated throughout history, recent decades have seen a "private museum boom" [[parencite:&Walker_2019_collector]] with hundreds of openings since 2000 [[parencite:&LarrysList_2015_report]].
#
Is their founding related to a decline of public institutions which shifts decision-making further into the hands of wealthy, private individuals who use the association of public benefit to legitimate increasing inequalities?
#
An analysis of the foundings of private museum constitutes a sofar unexploited opportunity to shed light onto larger questions of power arrangements. 


Multiple hypotheses for the spread of this new form have been raised, but systematic analyses of these have been lacking.
# 
In particular, the rise of private museums has been hypothesized to be associated to tax incentives, reductions in government spending, increasing inequality and increasing elite wealth.


Combining socio-economic and art field data sources, I conduct a quantitative test of these hypotheses of datasets of 1258, 2574 and 3400 country years using random effects negative binomial regression models.
#
While I find support for a role of tax incentives, government spending is found to be associated primarily positively (not, as hypothesized, negatively) with private museum founding.
#
Furthermore the effects of inequality are divergent, as a positive association with private museum founding is found for wealth inequality and a negative one for income inequality.
#
Finally, elite wealth effects are primarily negative and small.


** Delineating private museums
I use "private" to denote an organization established by a private art collector, art collector couple, or their descendants (excluding museums operated by companies or "the private sector" more generally) possessing a building and a collection of its own (excluding kunsthalles and exhibition centers) and being accessible to the public.
#
I also only include institutions that focus on modern or contemporary art (created after 1900).

** Theoretical background

*** Tax incentives

Tax incentives have been investigated as a explanatory factors of various kinds of philanthropic behavior and private museum founding in particular as they decrease the net cost of charitable activities. 
#
textcite:&Walker_2019_collector investigates the legal frameworks and tax exemptions that private museums receive in a number of regions, and concludes that "the formation of many private museums in the last two decades are directly or indirectly linked to generous tax incentives as they help to offset individual tax burdens and promote arts philanthropy." (p.37).

#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 1*: Higher Tax incentives are associated with more private museum founding.


*** State funding

The decline or absence of state support for the arts, particularly the acquisition budgets of public museums (either absolutely or relative to prices for contemporary art) also might lead to private museum founding [[parencite:&Brown_2019_private;&Quemin_2020_power]]. 
# 
As public museums constitute less attractive partners for private collectors for loaning, storing and buying their collections, private collectors might be incentivized to establish their own institutions.

Such substitutive relations between state and private funding are generally referred to as "crowding-out" in philanthropic studies (cf. [[cite:&Bekkers_Wiepking_2010_literature]]).
#
However, [[textcite:&DeWit_etal_2018_philanthropy]] and [[textcite:&Lena_2019_entitled]] argue that government funding could also signal valuation of an activity, which posits a positive association between government funding and private museum founding.

#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 2a*: Higher cultural spending is associated with less private museum founding.

#+latex: \noindent
*Hypothesis 2b*: Higher cultural spending is associated with more private museum founding.


*** Inequality
Critical Philanthropy Studies have argued for links between philanthropy more generally and distributional issues: 
#
For example, [[textcite:&Maclean_etal_2021_philanthropy]] argue that "the ultimate purpose of elite philanthropy [...] is to legitimate and make palatable the extreme inequalities generated by the forward march of global capitalism" (p.14), while [[textcite:&Glucksberg_RussellPrywata_2020_philanthropy]] argue that "philanthropy plays a role in helping elites legitimize their own wealth, and thus in legitimizing inequality" (p.2).

#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 3*: Higher income/wealth inequality is associated with more private museum founding.

*** Elite Wealth

The founding of private museums has been associated with the increase of (Very or Ultra) High Net Worth Individuals (HNWI, VHNWI, UHNWI; corresponding to a wealth of one, five and 30 million USD respectively) as these "spaces generate costs and mostly no incomes" (cite:&Gnyp_2015_collectors p.236), and hence can only be maintained by individuals with substantial disposable funds. 

#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 4*: Higher numbers of (V/U)HNWIs are associated with more private museum founding.

** Data

The unit of analysis constitutes a country-year (while collector-year would be preferable, no good longitudinal collector databases exist). 

*** Dependent Variable: Number of private museum foundings per country-year
To document the development of private museums, existing databases of private contemporary art museums parencite:LarrysList_2015_report,Independent_collectors,global_private_museum_network_2020_museums,BMW_Independent_Collectors_2018_artguide have been combined. 
#
Additionally, web research has been conducted by searching a number of online art media[fn::Artforum, Artnet, Art Territory, Artsy, My Art Guides, Artnews, Artfcity, Frieze, The Art Wolf, The Art Newspaper, Art Privee, Widewalls, White Hot Magazine, Hyperallergic.] for the terms "private museum", "private art museum" and "private contemporary art museum".
#
After determining status as private museum according to the definition used, country and opening year data was collected. 
#
Currently, the database includes 548 museums located in 63 countries, the majority being located in Western Europe (148), East Asia (96) and North America (84).
#
Country and opening year data is used to construct the DV of the number of private museums foundings per country-year.

*** Independent Variables
**** Tax incentives

The report "Rules to Give - A Global Philanthropy Legal Environment Index" [[parencite:&Quick_Kruse_Pickering_2014_philanthropy]] is used to construct a time-invariant (no longitudinal data sources exist) measure of tax deductibility of donations to non-profits. 
#
Top marginal income tax rate data is taken from the Index of Economic Freedom of the World parencite:&Fraser_2022_economic_freedom.
# 
As top marginal income tax rates are only expected to provide an incentive if tax donations are tax-deductible, I calculate an interaction term between the tax-deductibility of donations and marginal income tax rates.

**** Cultural Spending
I use data on government spending on culture, recreation and religion (COFOG8) collected by the UN [[parencite:&UN_2022_consumption]], the IMF [[parencite:&IMF_2022_GFS]], the OECD [[parencite:&OECD_2022_SNA_TABLE11_ARCHIVE;&OECD_2022_SNA_TABLE11]] and Eurostat [[parencite:&Eurostat_2022_COFOG]] as an indicator of cultural spending.
#
All money amounts are converted to 2021 USD using price indices and market exchange rates from the World Inequality Database [[citeyear:&WID_2021_WID]].

**** HNWIs
I use the Wealth Inequality Database (WID, [[citeyear:&WID_2021_WID]]) the number of HNWIs in a given country-year.
#
The WID contains for each country-year measures of the wealth at various quantile thresholds, i.e. the value for the 90th percentile describes the amount of wealth of the least wealthy member of the top 10%.
#
I use these thresholds to calculate the percentage of people above a certain threshold (I use thresholds of 1 million, 5 million, 30 million, 200 million USD) by linearly interpolating between the two nearest percentiles above and below the respective threshold.
#
The so-obtained proportion of HNWIs is converted into a count using population size from World Bank data.


**** Inequality
The WID provides gini coefficients for wealth and income; top 1% and 10% wealth and income shares are used as alternative measures of inequality. 


*** Control Variables
**** GDP per capita and Population size
Wealthier nations likely have larger population shares interested in art consumption, which possibly influences collectors choices of private museum founding.
#
Population size is included as an offset (see section [[id:80f8ba30-5754-4ca3-9602-4c93e85c75a0][Regression specification]]). 

**** Artnews collectors
As private museums are founded by collectors, they are more likely to be founded in country-years where more potential founders exist.
#
I thus construct a count indicator of the population of art collectors from the Artnews magazine collector ranking, an index published yearly since 1992 of the 200 art collectors the magazine considers most important.

**** Density dependence
Research on organizational population parencite:&Hannan_1992_dynamics has argued that foundings of organization are driven by legitimacy and competition, which are measured by indicators describing the organizational population. 
#
I therefore add a linear term (which measures legitimacy) and a squared term (which measures competition).
#
Given to the transnational nature of the art field I also add global linear and squared density measures.
#
I also control for a potential delegitimating effect of private museum closures (71 private museums have closed so far); due to the unequal distribution of these closures I only add a global count.

**** Museum population
Private museums can interact with other museums both competitively and cooperatively; I therefore use the Museums of the World database [[parencite:&deGruyter_2021_MOW]] to describe a country's art museum population.
#
Due to data limitations I construct a time-invariant indicators of the number (linear and squared) of modern and contemporary art museums opened until 1990.


** Analytical strategy

*** Variable combinations
Despite substantial efforts to collect complete data for the relevant variables, it was not possible to collect data for all country-years.
#
I therefore construct three datasets: one with all variables (1258 country years, 86 countries; referred to as "DS all IVs"), one with all variables except cultural spending (2574 country years, 153 countries; "DS --CuSp"), and one with all variables except cultural spending and marginal income tax rates (3400 country years, 163 countries; "DS --CuSp/TMITR").

*** Variable selection
As concrete operationalizations of variables have been absent, the particular variable for some concept is varied, namely for the number of HNWIs, thresholds of 1, 5, 30, 200 million USD, and for wealth and income inequality the 10% share, the 1% share the and gini coefficient.
#
This results in 36 possible variable sets (4 HNWI variables \times 3 income inequality variables \times 3 wealth inequality variables). 

*** Time lags
As the literature has not yet investigated the time different mechanisms need to create effects, I vary the time lag of each longitudinal variable between one and five years, and select the best-fitting one (with highest log-likelihood).
#
In total, 95 320 models are run. 


*** Regression specification
:PROPERTIES:
:ID:       80f8ba30-5754-4ca3-9602-4c93e85c75a0
:END:
Each regression model is specified as a negative binomial model using the xtnbreg command of Stata 14 with random country intercepts and population as an offset (all count predictors are therefore first transformed into per capita rates)
#
To facilitate convergence and interpretation, all non-binary variables are rescaled to a mean of 0 and a standard deviation of 1.

#+latex: \begin{landscape}
#+latex: \input{./tables/summary_stats.tex}
#+latex: \end{landscape}

** Results

#+label: plt_v62_coef_violin
#+caption: distribution of main coefficients
#+attr_latex: :width 16cm
[[file:figures/plt_v62_coef_violin.pdf]]


Coefficients are to be interpreted as logged multipliers of a country's private museum founding rate, therefore a coefficient of 0.2 corresponds to a exp(0.25) = 1.28 multiplier, i.e. a 28% increase in average country founding rate given a 1 standard deviation change in the independent variable.
#
Figure [[plt_v62_coef_violin]] shows the distribution of the main coefficients of the best fitting model of the 36 variable selections.

Tax deductibility of donations is positively associated with private museum founding in all datasets, supporting H1.

Government cultural spending shows a positive association with private museum founding.
# 
This finding thus does not support the crowding-out argument of the private museum literature (H2a).

For the inequality variables (H3) results are mixed as income inequality is associated negatively and wealth inequality positively with private museum founding. 

Finally, the effect of HNWIs (H4) is mostly negative and small in the two larger datasets, but differs between positive and negative depending on the HNWI threshold in the smallest dataset.

** Discussion and conclusion

This exploratory analysis gives insights to interpret the emergence of private museums.
#
While they seem to some extend supported by tax incentives, they so far do not seem to be indicative of a wider expansion of private elite influence as their openings follow state expenditure (rather than filling in gaps left by decreasing cultural spending).
#
Similarly, they are only weakly associated with increases of the HNWI population and show divergent relations to inequality.

The divergent effect of wealth and income inequality calls for both further theoretical elaboration and empirical analysis. 

* References :ignhead:
# \hypertarget{refs}{}

#+Latex: \begin{sloppypar}
#+Latex: \printbibliography
#+Latex: \end{sloppypar}



