#+latex_class: article_usual2
# erases make title
# #+BIND: org-export-latex-title-command ""

# fucks all the maketitlestuff just to be sure
#+OPTIONS: num:nil
#+OPTIONS: toc:nil
#+OPTIONS: h:5

#+BEGIN_SRC R :session calc :exports none :results values drawer
dt_nbrs <- fread("/home/johannes/Dropbox/phd/papers/org_pop/tables/tbl_nbrs.csv")
dt_nbrs[, .(sprintf("#+MACRO: %s %s", nbr_name, value))]
#+END_SRC

#+RESULTS:
:results:
#+MACRO: string_ensurer asdf
#+MACRO: nbr_muem_in_pmdb 547
#+MACRO: nbr_opnd_wld 516
#+MACRO: nbr_clsd_wld 78
#+MACRO: nbr_cry_wal1pm_all 64
#+MACRO: regsub_cnt_Western Europe 136
#+MACRO: regsub_cnt_Eastern Asia 97
#+MACRO: regsub_cnt_Northern America 77
#+MACRO: regsub_cnt_Southern Europe 71
#+MACRO: regsub_cnt_Northern Europe 27
#+MACRO: nbr_cy_cbn_all 1258
#+MACRO: nbr_cy_cbn_no_cult_spending 2574
#+MACRO: nbr_cy_cbn_no_cult_spending_and_mitr 3405
#+MACRO: nbr_crys_cbn_all 86
#+MACRO: nbr_crys_cbn_no_cult_spending 153
#+MACRO: nbr_crys_cbn_no_cult_spending_and_mitr 164
#+MACRO: nbr_opngs_cbn_all 360
#+MACRO: nbr_opngs_cbn_no_cult_spending 409
#+MACRO: nbr_opngs_cbn_no_cult_spending_and_mitr 411
#+MACRO: prop_opngs_cvrd_cbn_all 0.658
#+MACRO: prop_opngs_cvrd_cbn_no_cult_spending 0.748
#+MACRO: prop_opngs_cvrd_cbn_no_cult_spending_and_mitr 0.751
#+MACRO: nbr_mdl_started 76715
#+MACRO: nbr_mld_ended 76715
#+MACRO: opng_rate_cbn1 0.011
#+MACRO: opng_rate_cbn2 0.0060
#+MACRO: opng_rate_cbn3 0.0046
#+MACRO: nbr_zero_cbn_all 1 043
#+MACRO: nbr_nzero_cbn_all 215
#+MACRO: prop_nzero_cbn_all 17.1
#+MACRO: nbr_zero_cbn_no_cult_spending 2 316
#+MACRO: nbr_nzero_cbn_no_cult_spending 258
#+MACRO: prop_nzero_cbn_no_cult_spending 10.0
#+MACRO: nbr_zero_cbn_no_cult_spending_and_mitr 3 145
#+MACRO: nbr_nzero_cbn_no_cult_spending_and_mitr 260
#+MACRO: prop_nzero_cbn_no_cult_spending_and_mitr 7.6
#+MACRO: nbr_zero_cbn_controls 5 931
#+MACRO: nbr_nzero_cbn_controls 301
#+MACRO: prop_nzero_cbn_controls 4.8
#+MACRO: nbr_pop_p_1pm_cbn_all 89.7
#+MACRO: nbr_pop_p_1pm_cbn_no_cult_spending 165
#+MACRO: nbr_pop_p_1pm_cbn_no_cult_spending_and_mitr 215
#+MACRO: nbr_pop_p_1pm_cbn_controls 85.0
#+MACRO: rate_opng_glbl_cbn_all 0.00433
#+MACRO: rate_opng_glbl_cbn_no_cult_spending 0.003
#+MACRO: rate_opng_glbl_cbn_no_cult_spending_and_mitr 0.00283
#+MACRO: rate_opng_glbl_cbn_controls 0.00231
#+MACRO: rate_opng_glbl_yearly_cbn_all 0.00404
#+MACRO: rate_opng_glbl_yearly_cbn_no_cult_spending 0.00292
#+MACRO: rate_opng_glbl_yearly_cbn_no_cult_spending_and_mitr 0.00279
#+MACRO: rate_opng_glbl_yearly_cbn_controls 0.00223
#+MACRO: cvrgd1 76 455
#+MACRO: cvrgd0 260
#+MACRO: mdlcnt_ttl 76 715
#+MACRO: cvrgnc_rate 99.7
#+MACRO: nbr_runs_p_cbn_spec 142
#+MACRO: txdctblt_cbn3 0.74
#+MACRO: txdctblt_cbn3_exp 2.1
#+MACRO: txdctblt_cbn2 0.46
#+MACRO: tmitr_cbn2 -0.36
#+MACRO: txdctblt_tmitr_interact_cbn2 0.75
#+MACRO: txdctblt_tmitr_interact_cbn2_exp 2.1
#+MACRO: tmitr_1SD_cbn_all 14.2
#+MACRO: smorc_lin 0.36
#+MACRO: smorc_lin_flipped -0.36
#+MACRO: smorc_sqrd -0.64
#+MACRO: smorc_top_point_std 0.28
#+MACRO: smorc_top_point 433
#+MACRO: intcpt -2.22
#+MACRO: intcpt_exp 0.108
#+MACRO: smorc_2020_ITA 362
#+MACRO: smorc_2020_SVK 415
#+MACRO: smorc_2020_ARE 440
#+MACRO: smorc_2020_NZL 463
#+MACRO: smorc_2020_POL 466
#+MACRO: smorc_2020_LVA 467
#+MACRO: smorc_2020_AUS 499
#+MACRO: smorc_2020_ESP 501
#+MACRO: smorc_2020_CAN 513
#+MACRO: smorc_2020_CZE 634
#+MACRO: smorc_2020_DEU 660
#+MACRO: smorc_2020_FRA 680
#+MACRO: smorc_2020_BEL 688
#+MACRO: smorc_2020_AUT 694
#+MACRO: smorc_2020_NLD 782
#+MACRO: smorc_2020_FIN 799
#+MACRO: smorc_2020_CHE 806
#+MACRO: smorc_2020_EST 819
#+MACRO: smorc_2020_SWE 859
#+MACRO: smorc_2020_DNK 1 058
#+MACRO: smorc_2020_HUN 1 410
#+MACRO: smorc_2020_NOR 1 544
#+MACRO: smorc_2020_LUX 1 559
#+MACRO: smorctop_below_CYs_cnt 815
#+MACRO: smorctop_above_CYs_cnt 443
#+MACRO: smorctop_below_nbr_opened_cnt 214
#+MACRO: smorctop_above_nbr_opened_cnt 146
#+MACRO: smorctop_below_CYs_prop 64.8
#+MACRO: smorctop_above_CYs_prop 35.2
#+MACRO: smorctop_below_nbr_opened_prop 59.4
#+MACRO: smorctop_above_nbr_opened_prop 40.6
:end:




* Investigating causes of private museum funding

** abstract
#
In the last decades a new organizational population of private museums has seen substantial proliferation.
#
While multiple hypotheses for the spread of this new form have been raised, systematic analyses of these have been lacking.
#
In particular, the rise of private museums has been hypothesized to be associated to tax incentives, reductions in government spending, increasing inequality and increasing elite wealth. 
#
Combining various socio-economic and art field data sources, I conduct a quantitative test of these hypotheses of datasets of 1258, 2574 and 3400 country years using random effects negative binomial regression models.
#
While I find moderate support for a role of tax incentives, government spending is found to be associated primarily positively (not, as hypothesized, negatively) with private museum founding.
#
Furthermore the effects of inequality are divergent, as a positive association with private museum founding is found for wealth inequality and a negative one for income inequality.
#
Finally, elite wealth effects are primarily negative (some although are positive) as well as small.
#
I conclude with a call for greater theoretical elaboration and measurement precision to further investigate founding causes.



** Introduction
Private museums constitute a substantial development in the cultural sector in the last decades.
#
While museums have been privately founded throughout history, recent decades have seen an increase in their founding that has been coined the "private museum boom" [[parencite:&Walker_2019_collector]], which has resulted in hundreds of private museums being founded since 2000.
#
These institutions can vary substantially in their organizational characteristics such as size, number of visitors, and professionalism, thus ranging from small house museums open only by appointment to "full-service" institutions with large numbers of visitors, sophisticatedly curated exhibitions as well as conservation and research programs.


Effectively delineating private museums is not a straightforward task, and depends on the conceptualization of the terms "private" and "museum", neither of which are unambiguous concepts either.
#
For this study I use "private" to denote being established by a private art collector, art collector couple, or their descendants; such a focus on the individual founder thus does not include museums operated by companies (what may more generally be called the "private sector") or groups of people.
#
A "museum" is conceptualized as an organization that possesses a building and a collection of its own (which excludes kunsthalles and exhibition centers), which is sufficiently accessible to the public.
#
For the purpose of this research I also only include such institutions that focuses on modern or contemporary art, with modern and contemporary art operationalized as art created after 1900. 


These institutions raise a number of questions:
#
While private initiative in the art field is not new (the guilded age also saw many private museums, and many private actors are active in the art field more generally such as such as dealers, critics, artists themselves and collectors), collectors have recently engaged in a new activity of not just collecting artworks, but also making them accessible to the public.
#
So far it is difficult both to place this development in the wider context of the fields of art and power and anticipate its consequences.
#
Are private museums a short-lived fad, or will they leave a lasting impact in the art field, potentially wrangling consecrating power from other museums?
#
Not all of these question I am able to address, yet I argue that to understand the development of the organizational form of private museums and estimate their consequences it is necessary to first study why these institutions came into existence in the first place. 


Thus in this study I focus on the process of founding a private museum.
#
The literature has proposed a number of factors that might have facilitated their founding, namely tax incentives, (lack of) state funding, inequality and  elite wealth.
#
However, previous research has been primarily conducted as case studies of individual museums (sometimes based on fieldwork, but often also only on media reports); systematic comparative work has so far been limited.
#
Furthermore, by focusing on museums that have been founded, existing research has generally sampled on the dependent variable; i.e. limited attention has been given to countries without substantial private museum founding (and to a lesser extent time periods, as previous studies often do discuss the longitudinal development of the country where the cases are located). 
#
At the same time, substantial interest in the general population of private museum exists:
#
Many publications refer to the first published systematic account of the overall private museum population [[parencite:&LarrysList_2015_report]], yet then can only make limited inferences/statements as the case studies only allow limited generalization to the entire population (a limitation which is further enhanced through a selective focus on high-profile private museums). 


Thus much is to be gained from a systematic quantitative test of these different mechanisms.
#
As the quantitative private museum literature is still it its infancy, this paper should be understood as a first exploratory analysis that hopefully will be refined in the future. 
#
In the remainder of the paper, I review the literature on the causes of private museum founding, and describe the data sources used to investigate each mechanism.
#
I then conduct several regression analyses to investigate the impact that each of the main mechanisms (tax incentives, government spending, inequality and elite wealth).
#
I find support for a positive effect of tax incentives, a positive effect of cultural spending, divergent effects of different inequality measures and limited support for an effect of elite wealth.


** Introduction2
Private museums constitute a substantial development in the cultural sector in the last decades.
#
While museums have been privately founded throughout history, recent decades have seen an increase in their founding that has been coined the "private museum boom" [[parencite:&Walker_2019_collector]], which has resulted in hundreds of private museums being founded since 2000.
#
These institutions, often opened by extremely wealthy art collectors, have attracted substantial attention and controversy.
#
Evaluations can range from lauding the public-spiritedness of the founders who expend large sums of their private wealth for the provision of public goods to criticisms of the unaccountability and questions of the sustainability and quality of these institutions, as well as the status-seeking behavior of their founders.
#
Just as their present behavior and its consequences has aroused curiousity, so has the question of which factors led to their proliferation in the first place:
#
Is their founding related to a decline of public institutions which shifts decision-making further into the hands of wealthy, private individuals who use the association of public benefit to legitimate increasing inequalities?



To answer these questions, I investigate in this paper  the structural conditions that resulted in the proliferation of private museums as an organizational form over the course of the last decades.
#
As the spread of private museums has attracted attention, a number of factors have been suggested that have facilitated their founding, namely tax incentives, (lack of) state funding, inequality and elite wealth.
#
However, previous research has been primarily conducted as case studies of individual museums (sometimes based on fieldwork, but often also only on media reports); systematic comparative work has so far been limited.
#
Furthermore, by focusing on museums that have been founded, existing research has generally sampled on the dependent variable; i.e. limited attention has been given to countries without substantial private museum founding (and to a lesser extent time periods, as previous studies often do discuss the longitudinal development of the country where the cases are located). 
#
At the same time, substantial interest in the general population of private museum exists:
#
Many publications refer to the first published systematic account of the overall private museum population [[parencite:&LarrysList_2015_report]], yet then can only make limited inferences/statements as the case studies only allow limited generalization to the entire population (a limitation which is further enhanced through a selective focus on high-profile private museums).


Thus much is to be gained from a systematic quantitative test of these different mechanisms.
#
As the quantitative private museum literature is still it its infancy, this paper should be understood as a first exploratory analysis that hopefully will be refined in the future. 
#
In the remainder of the paper, I review the literature on the causes of private museum founding, and describe the data sources used to investigate each mechanism.
#
I then conduct several regression analyses to investigate the impact that each of the main mechanisms (tax incentives, government spending, inequality and elite wealth).
#
I find support for a positive effect of tax incentives, a positive effect of cultural spending, divergent effects of different inequality measures and limited support for an effect of elite wealth.

** Theoretical framework


# The private museum population of a country can be thought of as the result of many different processes; for this analysis, it is most suitable to distinguish between micro and macro processes.
# #
# While the data only allows a purely macro perspective, it is still necessary to explicitly consider the microfoundations which in aggregation produce the observed macro outcome (of private museums founded per country year). 
# # 
# On a micro-level, tax incentives, inequalities, and cultural spending are hypothesized to influence the likelihood of any potential founder to establish a private museum.
# #
# Independent of the motivations on the individual level, other factors are assumed to influence/account for the size of the population of potential founders.
# #
# On a macro-level, the number of High Net Worth Individuals (HNWIs) are hypothesized to be related to the number of potential founders. 
# # 
# The necessity of considering the contribution to private museum founding of both these mechanisms can be illustrated by comparing a country with limited incentives for the individual art collectors but a large population of potential founders, which due to its large population of founders  might still see equal or more private museums foundings compared to a country with a much smaller, more incentivized population of potential founders. 



# *** Collector Level 

*** Tax Incentives

**** general :ignhead:

Tax incentives have been investigated as a factor for influencing various kinds of charitable or philanthropic behavior and private museum founding in particular.
#
Tax incentives decrease the net cost of charitable activities, and can thus be expected to shape philanthropic behavior to the extent to which these activities are not unconditional of economic considerations[fn::While themes of disinterestedness and intrinsic passion are strongly present in the self-presentations of founders [[parencite:&BMW_2016_hall;&Bechtler_Imhof_2018_future;&Duron_2020_rebaudengo]], they might constitute strategic framings to adhere to art market norms [[parencite:&Velthuis_2007_talking]] rather than real motivations guiding actual behavior.]. 
#
Investigating charitable donations more generally, [[textcite:&Peloza_Steel_2005_elasticities]] find in a meta-analysis (primarily of individual behavior in the US) a price-elasticity of donations, i.e. a stronger tendency to make charitable contributions in the presence of financial incentives.



**** pro :ignhead:

Tax incentives, such as exemption of charitable organizations from some taxes and tax deductibility of donations to such organizations, have also been argued to contribute to the founding of private museums.
#
textcite:&Walker_2019_collector investigates the legal frameworks and tax exemptions that private museums receive in a number of locations.[fn::A historical argument is also made regarding the precursors of private museums, as tax incentives are also seen as relevant to the establishment of art collections in the gilded age as "the accumulation of expensive European art collections at the turn of the twentieth century was aided by the reduction, and eventual abolition of import tariffs in the US" (p.27).]
#
In the case of Australia, she argues that tax reforms that increased tax deductions for donations to charitable organizations played a substantial role for the establishment of private museums: "The founding and funding of TWMA [TarraWarra Museum of Art] was a direct consequence of the changes to Australian tax law. [...] without [a broader range of inducements and approaches], I would suggest a generosity of spirit alone will not result in a substantial philanthropic gift such as TWMA or the founding of other private museums in Australia."
#
In the US, the tax code is also argued to "[support] the founding of collector museums" (p.35) through incentives such as exemptions from capital gains tax and tax deductibility of exhibition, insurance, conservation and storage costs.


For Europe, the effect of tax incentives on founding is less pronounced.
#
While tax incentives in Germany (p.29) and Switzerland (p.36) are discussed, it is not argued that they constitute a necessary or supportive factor in the establishment of private museums, it is merely mentioned that "[their] complex tax structure is a way for [a] foundation to minimize its tax burden." (p.36).
#
Nevertheless, a clear overall argument is reached in the impact of tax incentives as it is concluded that "the formation of many private museums in the last two decades are directly or indirectly linked to generous tax incentives as they help to offset individual tax burdens and promote arts philanthropy. [...] The generosity and breadth of American, Australian, English and European tax law is a factor in the promotion of private museums" (p.37). 



**** contra :ignhead:

# fixme: check sentence structure: list lacking verb?
The impact of tax incentives does not exclude other motivations, thus arguments which highlight other motivations such as "passion for art" ([[cite:&Zorloni_Resch_2016_opportunities p.7]], [[cite:&Adam_2021_rise p.12]]) or other "personal motivations" [[parencite:&Walker_2019_collector p.144]] do not contradict a facilitative role of tax incentives. 
#
In fact, other motivations (such as the aforementioned passion for the arts, as well as potential reputation gains; cf. [[cite:&Bekkers_Wiepking_2010_literature;&Bekkers_Wiepking_2011_philanthropic]] for motivations of philanthropic behavior generally) are required as tax incentives only /reduce/ the cost of philanthropic behavior but do not cancel it out completely, let alone result in a financial profit; tax incentives thus may play a supportive role by easing the financial burdens of running a private museum as a consequence of other motivations.


However, an different reason why tax incentives might not have noticeable effects might be their limited knowledge and familiarity among potential beneficiaries (collectors deliberating the choice of opening a museum), a mechanism which has been argued to negatively affect private museum founding in China [[parencite:&DeNigris_2018_museums p.222]] and charitable donations in Europe generally [[parencite:&Hemels_2017_incentives;&Stanco_2014_fiscaal]].
#
While lack of familiarity might prevent an effect of tax incentives that exist, it seems unlikely to be the case here as the topic of tax incentives has found substantive coverage in publications both scholarly parencite:Walker_2019_collector,Reich_2018_philantropy,Zorloni_2016_artmanagement,Zolberg_2000_privatization and journalistic (e.g. cite:Brown_Pes_2018_taxpayers,Boucher_2020_solow,Halperin_2018_glenstone,Honig_2016_IRS).
#
Furthermore, the decision of opening a private museum is likely receiving more deliberation than smaller acts of philanthropy (such as donations) due to the size of the necessary planning efforts (which sometimes results in the establishment of separate foundations staffed by professionals); it is hence unlikely that during this planning process financing pathways through tax incentives are not explored.


It thus seems plausible to assume an influence of tax breaks, leading to the following hypothesis:

#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 1*: Tax incentives are associated with higher rates of private museum founding.


*** State funding


**** pro :ignhead:

Another argument for the emergence of private museums has been the decline or absence of state support for the arts. 
#
Whereas in the mid-to-late 20th century "wealthy industrialist collectors [...] looked to the public museum as a suitable home for their collections" [[parencite:&Walker_2019_collector p.144]], declines in cultural spending are argued to have reduced public museum capacities, thus making them less attractive for conserving, displaying and storaging donations of private collectors, which in turn leads "many collectors [to] feel that they are better qualified to create their own museums" (ibid, p.145).
#
While some forms of public-private partnerships "[appear] to contradict the premise that many private museums are founded because of the weakness of the public sector and the limitations of the public museum" (p.150),  [[textcite:&Walker_2019_collector]] nevertheless argues that "the growing popularity of German private collector museums can be attributed to the difficult economic climate that is negatively impacting public museums" (p.146). 
# 
Similarly, textcite:&Boloten_Hacking_2021_foreword argue that "with their inevitably strained resources, public museums often struggle to satisfy the substantial demands of the collector/patron communities on which their collections, and institutions, very much rely. Against this backdrop [...] [art collectors] are increasingly turning to bespoke Private Museum solutions" (p.10). 
#
In particular, limited exhibition space in public museums has been argued to have been contributed to the rise of private museums ([[cite:&Walker_2019_collector p.217]], [[cite:&Zorloni_Resch_2016_opportunities p.1]]). 
#
Additionally, textcite:&Franklin_Papastergiadis_2017_anti argue that private museums "became prominent once the price of contemporary art inflated beyond the means of most cash-strapped public museums to collect it systematically" (p.672)[fn:: While it is however not completely clear whether this refers to operations or acquisitions budgets, I argue that the general relation between public museum capacities and private museum founding is argued for clearly.]
#
Another pathway between low public funding and relatively high private museum founding concerns emerging art markets in developing countries, as it is argued that private individuals are more likely dedicate philanthropic efforts to the arts there than in places where it is already supported by the state [[parencite:&Durand_2018_jumex;&Bechtler_Imhof_2018_future;&Boloten_Hacking_2021_foreword]], a pattern that could correspond to the founding of gilded age cultural institutions by industrialists in the late 19th/early 20th century [[parencite:&diMaggio_1982_boston;&Adam_2004_philanthropy;&Duncan_1995_civilizing]]. 
 

# In the private museum literature more widely declining acquisition budgets (either in absolute terms or relatively to the ostensibly strongly increasing prices for contemporary art) of public museums are also discussed, but primarily related to increasing influence of private museum on canonization processes [[parencite:&Walker_2019_collector;&Gnyp_2015_collectors;&Bechtler_Imhof_2018_future;&Quemin_2020_power]]. A relationship to the founding of private museums is not made, presumably since declining acquisition alone would presumably not raise a collector's likelihood of founding a private museum. 

# On the contrary, the acquisition budgets of private museums are characterized as much less restricted, enabling them to outbid their public counterparts [[parencite:&Durand_2018_jumex;&Bechtler_Imhof_2018_future;&Gnyp_2015_collectors]].

# [[parencite:&Bechtler_Imhof_2018_future;&Walker_2019_collector;&Franklin_Papastergiadis_2017_anti]]
#
# [[textcite:&Walker_2019_collector]] also describes several cases of public museums selling parts of their collections to offset debts (p.146), which could also point towards declines in public spending. *but no reason why this should increase PM founding: argument could be less symbolic capital/competition*


**** contra :ignhead:

Such theorized substitutive relations between state and private funding are more generally referred to as "crowding-out" in philanthropic studies (cf. [[cite:&Bekkers_Wiepking_2010_literature]] for a literature review;  the lack of engagement with the term and related studies thus also indicates the early state of theoretical development of the private museum literature).
#
The term "crowding-out" originated in response to the question of how charitable behavior would change if states were to /increase/ funding, thus potentially "crowding out" private donors.
#
While the situation is a different one here, with private museum founding being related to /decreasing/ state funding (or the absence of it), the underlying theoretical mechanism is the same:
#
In both cases, donors are motivated (for altruistic or other reasons) to provide of public goods, and thus allocate their donations in response to the funding choices of the government.
#
However, [[textcite:&DeWit_etal_2018_philanthropy]] and [[textcite:&Lena_2019_entitled]] argue that government funding could also signal valuation of an activity, which raises the possibility of a positive association between government funding and private museum founding ("crowding-in").
# 
Nevertheless, as the crowding-in hypothesis has not been employed in the case of private museums, the hypothesized effect of government funding based on the private museum literature can be formulated as follows:  

#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 2*: Higher government cultural spending is associated with lower rates of private museum founding.


*** Inequality

In the private museum literature, distribution of wealth and incomes has received only limited attention.
# this actually is not that explicit either
The only explicit argument regarding /inequality/ on its own (separate from the high absolute sums of wealth) is made by [[textcite:&Brown_2019_private]], who points out parallels to previous periods of wealth accumulation by arguing that "the founding of private museums appeals to the rhetoric of social obligation that sustained the accumulation of capital early in the twentieth century and that induced publics not to object to the rise to power of wealthy classes" (p.15).
#
Contemporary society is argued to resemble again the gilded age of the late 19th and early 20th century where  "acts of philanthropic giving [...] functioned as a means by which to maintain widespread confidence in a socio-economic system that enabled a small social cadre to accrue long-term financial advantage" (p.3). 
#
Rising inequality is argued to create a legitimacy deficit, to which the founding of private museums provides a not a substantial solution, but a distraction which despite being superficial seems to be effective nonetheless.





While [[textcite:&Brown_2019_private]] is alone in making an explicit argument for a relationship between private museum founding and inequalities (as other mentions of inequality, such as [[textcite:&KalbCosmo_2020_museum]] or [[textcite:&Adam_2021_rise]] do not raise a specific relationship between inequality and private museum founding[fn::[[textcite:&Adam_2021_rise]] however argues that "[private museums] highlight the glaring wealth inequality of our time" (p.86)]), a literature stream that might be best summarized as "critical philanthropy studies" has argued for links between philanthropy more generally and distributional issues: 
#
For example, [[textcite:&Maclean_etal_2021_philanthropy]] argue that "the ultimate purpose of elite philanthropy [...] is to legitimate and make palatable the extreme inequalities generated by the forward march of global capitalism" (p.14)
# 
A similar arguments are made by [[textcite:&Glucksberg_RussellPrywata_2020_philanthropy]], who compare the philanthropic donations of the most charitable givers to their business activities, after finding the former to be dwarfed by the latter, argue that "philanthropy plays a role in helping elites legitimize their own wealth, and thus in legitimizing inequality" (p.2).
#
[[textcite:&Giridharadas_2018_winners]] argues that inequality causes dissatisfaction, leading philanthropists to engage in philanthropy "out of a mix of altruism and the self-preservational desire to cool public anger" (p.172).
#
textcite:&KohlArenas_2015_selfhelp argues that "private foundations and social movement organizations construct idealized spaces of public participation and discourse theories of change that draw attention away from structural inequality" (p.796). 
#
Less explicit about mechanisms, vague associations between philanthropy and inequality are also raised by [[textcite:&Reich_2018_philantropy]] as "growth in inequality might be a foe to civil comity, but it is a friend to private philanthropy" (p.9).
# 
As these scholars unanimously posit a positive association between inequality and philanthropy, the hypothesis can be formulated as: 

# not considered here is the argument of inequality leading to philanthropy through the mechanism of material [[mechanism of of A growing gap between the rich and poor has created a growing number of mega-wealthy individuals who can give and a growing number of poor people in need of such gifts. (p.586) cite:&Eikenberry_2006_governance]]

# cite:&Kolbe_forthcoming_legitimization
# PM burns money -> is good
# gift lol
# but is more about founder status, not necessarily inequality
# could make inequality argument if there was country with little inequality and little founder status boasting
# -> just hard to make statement about inequality if you have no variation in it? constant background variable

#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 3*: Higher income and/or wealth inequality is associated with higher rates of private museum founding.



*** Elite Wealth

The founding of private museums has been associated with the rise of (Very or Ultra) High Net Worth Individuals (HNWI, VHNWI, UHNWI; corresponding to a wealth of 1 million, 5 million and 30 million USD respectively).
#
[[textcite:&Gnyp_2015_collectors]] notes that a "reason for the rise of private museums could be the accumulation
of wealth of the UHNWIs, whose income and numbers have been growing" (p.145).
#
Similarly, textcite:&Zorloni_Resch_2016_opportunities argue that "due to [...] the increasing number of HNWIs, the number of private museums has been increasing in recent years" (p.12).
#
# nope this is all about new collectors being different
Less explicit about a connection between elite wealth and private museum founding, textcite:&Walker_2019_collector notes that "rapid increases in [...] private wealth" (p.145) as one of the conditions that strengthened the position of collectors vis-a-vis public museums, presumably as wealth increases allowed them to set up their private museums. 
#
As it has been argued that "such private spaces cost money and often do not generate any income" [[parencite:&Gnyp_2015_collectors p.145]], they are only feasible to maintain by individuals with substantial disposable funds. 



However, there have also been calls to caution against an exclusive focus on "super rich collectors who attract so much attention [as] there are many others that have made and still make things possible with comparatively small means" [[parencite:&Bechtler_Imhof_2018_future p.12]].
#
However, even the "comparatively small means" that textcite:&Bechtler_Imhof_2018_future refer to are presumably "comparatively small" only in relation to the absolutely richest individuals (e.g. billionaires), and are thus presumably still located in the range of what would be classified as HNWIs.
# 
A hypothesis on elite wealth can thus be formulated as: 

#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 4*: Higher numbers of (V/U)HNWIs are associated with higher rates of private museum founding.


# Private museums are also associated specifically with the nouveau riche, for example in the American gilded age [[parencite:&Duncan_1995_civilizing;&Walker_2019_collector;&Higonnet_2003_sight;&Higonnet_2007_selfportrait]] or contemporary China [[parencite:&DeNigris_2018_museums;&Lu_2014_museums]]; here these institutions are argued to signal cultural capital and generate symbolic capital to help newcomers integrate into established elite circles.


# #+latex: \noindent
# *Hypothesis 3*: Larger shares of nouveau rich are associated with higher rates of private museums founding.
# #+latex: \bigbreak


** Data

Ideally collector-level data would be used to construct collector-year as the unit of analysis, which would allow the investigation of collector decision-making by utilizing collector-level variables. 
#
However, no such databases exist of the art collector population, in particular regarding its longitudinal development, to make such an analysis feasible.
# 
Therefore the more aggregate unit country-years is used as the unit of analysis, which results in a panel data analysis.
#


*** Dependent Variable: Number of private museum foundings per country-year

#+label: fig:openings
#+caption: Private Museum openings (absolute and population-rate) of 12 countries with highest counts. 
[[file:figures/foundings_country_cnt_and_rate.pdf]]


To document the development of private museums, existing databases of private contemporary art museums parencite:LarrysList_2015_report,Independent_collectors,global_private_museum_network_2020_museums,BMW_Independent_Collectors_2018_artguide,vdEerenbeemt_vdWauw_DDD_2016 have been combined.
#
Additionally, web research has been conducted by searching in a number of online art media[fn::The media sources used were: Artforum, Artnet, Art Territory, Artsy, My Art Guides, Artnews, Artfcity, Frieze, The Art Wolf, The Art Newspaper, Art Privee, Widewalls, White Hot Magazine and Hyperallergic.] for the term "private museum", "private art museum" and "private contemporary art museum".
#
After recording the names and deleting duplicates, it was investigated using publicly available information whether the organization corresponds to the employed definition of a private museum.
#
Following this, additional information about each museum was collected by student assistants, the most relevant for this research being country and opening year.
#
Currently, the database includes 547 museums (of which 446 are currently open), located in 63 countries, with the majority being located in Western Europe (136), East Asia (97) and North America (77).
#
Information on country and opening year is used to construct a count indicator of the number of private museums opened in each country-year.
#
This study has a global scope (it includes the large number of countries without private museums to avoid sampling on the dependent variable) and while ideally it would cover all country-years from 1985 onwards (which is approximately when the current wave of founding started; see figure [[fig:openings]]), however both the time period and number of countries that can be investigated are limited by the coverage of the independent variables. 


*** Independent Variables
**** Tax incentives
#
For this study, I focus on top marginal income tax rates, i.e. the amount of tax to be paid on income in the uppermost tax bracket, and tax deductibility of donations.
#
Higher marginal income tax rates (in combination with tax deductibility of charitable donations) decrease the net cost of a donation (as higher rates increase the amount of taxes returned; cf. cite:&Hemels_2017_incentives for a more detailed discussion), and are thus expected to increase the incentive for founders to donate their collection (or parts of it) to their private museum and receive a tax deduction in return. 


Top marginal income tax rate data is taken from the Index of Economic Freedom of the World parencite:&Fraser_2022_economic_freedom, of which it constitutes a sub-item.
# 
Tax deductibility of donations is measured from the report "Rules to Give - A Global Philanthropy Legal Environment Index" [[parencite:&Quick_Kruse_Pickering_2014_philanthropy]].
#
I use the binary indicator measuring whether individuals can receive tax deductions for donations to non-profits[fn::The report also includes a binary indicator whether non-profit organizations are exempt from at least some taxes, but as this is the case in the vast majority of countries, it does not provide sufficient variation to serve as an explantory variable.].
#
The report describes the situtation in 193 countries but only covers the state of the legal environment at its publication date, therefore tax deductibility of donations can only be investigated in regards to between-country differences.
#
# As I have been unable to find good longitudinal data sources on tax deductibility of donations that covers large numbers of countries (especially for the earlier parts of the time period) tax deductibility of donations can only be investigated in regards to between-country differences.
# 
As top marginal income tax rates are only expected to provide an incentive if tax donations are tax deductible, I calculate an interaction term between the tax deductibility of donations and marginal income tax rates. 
# (as tax deductibility is a binary variable, the value of the interaction term is 0 for countries in which charitable donations are not tax-deductible, and the value of top marginal income tax rates otherwise).
 
**** Cultural Spending

I use data on government spending on culture, recreation and religion collected by the UN [[parencite:&UN_2022_consumption]], the IMF [[parencite:&IMF_2022_GFS]], the OECD [[parencite:&OECD_2022_SNA_TABLE11_ARCHIVE;&OECD_2022_SNA_TABLE11]] and Eurostat [[parencite:&Eurostat_2022_COFOG]] as an indicator of cultural spending.
#
These organizations use the System of National Accounts (SNA), where Classification of the function of government (COFOG) Code 8 describes "culture, recreation and religion".
#
The single digit code 8 is rather broad, and the more detailed  double digit SNA code 82 "cultural services" would be preferable to exclude state spending on e.g. sport events, broadcasting, publishing and religion. 
#
However, data coverage is substantially worse for SNA Code 82, and as there appears to be substantial correlation between Codes 8 and 82 for countries that provide data on both levels, I consider it acceptable to use the broader single-digit Code 8.
#
As even with the broader single-digit Code 8, cultural spending constitutes the indicators with the least coverage, I furthermore combine as many data sources as possible.


This combination of the different data sources requires the harmonization of different reporting standards: 
#
Whereas the the IMF and Eurostat report data exclusively as "Total government expenditure" (TLYCG), the UN uses "Final consumption expenditure" (P3CG); the OECD reports data in both formats ("Total government expenditure" is calculated from "Final consumption expenditure" as well as a number of other items, such as compensation of employees, subsidies and property income). 
#
Furthermore within each format, minor variations exist between data sources, the data for a country-year is thus chosen in order of OECD followed by UN for P3CG, and OECD followed by IMF followed by Eurostat for TLYCG (for the UN data, sometimes data is also reported in multiple Series corresponding to different SNA methodologies (see [[textcite:&UN_2022_consumption]] footnote 2 for details); here SNA 2008 methodology is chosen if available, otherwise the mean of the other series is taken).


As the overall goal is to create a complete picture of government expenditure, Total government expenditure has to be estimated based on Final consumption expenditure for country-years where data is only available for the latter.
# 
For countries where TLYCG and P3CG series have some overlap and years exist with P3CG data but not TLYCG data, a country-specific scaler to convert P3CG to TLYCG is constructed based on the years in which the series overlap, which is then used to impute TLYCG for the years in which only P3CG data is available.
#
For countries with only P3CG data, the average ratio of all country-years with both P3CG and TLYCG data is chosen to impute TLYCG (as on average P3CG is 58% of TLYCG, the average scaler is 1/0.58 = 1.72). 
#
As the amounts reported are in current local currency units, they are converted to 2021 USD using price indices and purchasing power parity adjusted exchange rates from the World Inequality Database (WID,  [[citeyear:&WID_2021_WID]]).
# [fn::An alternative would be to use purchasing power parity exchange rates, which reflect local price levels (as [[textcite:&Blanchet_2017_conversions]] argues, 1 euro or 7 yuan allow the purchase of the same amount of oil on international markets, but different amounts of food in Beijing or Paris). As the art market is however substantially transnational [[parencite:&Velthuis_Curioni_2015_canvases]], and discussion of government spending heavily revolves around acquisition budgets (which are dedicated to the purchase of artworks that often are  international), I consider market exchange rates more appropriate.]


**** Inequality
The WID also provides Gini coefficients for wealth and pre-tax income[fn::While data on post-tax income is also included, its coverage is very limited].
#
The top 1% and 10% wealth and income shares are used as alternative measures of inequality, as these measures are commonly used in in WID publications.


**** High Net Worth Individuals
I also use the WID to calculate the first the percentage, and then the number of High Net Worth Individuals (HNWI), i.e. the population above a certain wealth threshold in a given year. 
#
The WID contains for each country-year measures of the wealth at various quantile thresholds, i.e. the value for the 90th percentile describes the amount of wealth of the least wealthy member of the top 10%.
#
With higher quantiles, higher resolutions are included: Up to the 99th percentile, the largest step is 1% (e.g. 91,92,93th etc quantile), while the 99th percentile is subdivided further into percentile tenths (99.1,99.2 etc).
#
The top 0.1% and 0.01% (the 99.9th and 99.99th quantile) are also similarly subdivided into ten smaller slices (although the degree to which this information is available varies between country-years).
#
Amounts are reported in local currencies and are therefore converted into 2021 USD using market exchange rates provided by the WID.
#
I use these thresholds to calculate the percentage of people above a certain threshold (I use thresholds of 1 million, 5 million, 30 million, 200 million USD[fn::Despite the large number of thresholds and the increases of resolution in the higher percentiles, I do not consider it adequate to measure numbers at higher thresholds than 200M. It it is thus unfortunately not possible to measure the effect of billionaires which receive much media attention.]) by linearly interpolating between the two nearest percentiles above and below the respective threshold.
#
If the threshold exceeds the value of the highest quantile, I assign a zero.[fn::Linear interpolation likely overestimates the percentage of HNWIs for cases where data on at least one higher threshold exists (as the wealth distribution probably does not increase linearly), and underestimates it when no higher threshold exists (as necessarily 0 is assigned). Nevertheless, I argue that the possibility to set arbitrary wealth thresholds provides valuable insights.]
#
The so-obtained proportion of HNWIs is converted into a count using World Bank population size data.


*** Control Variables
**** Gross domestic product and Population size
#
GDP is included to account for potentially imperfect measurement of government spending and other art scene indicators (discussed below). 
#
Furthermore, given he stratified character of art consumption [[parencite:&Bourdieu_1984_distinction]] within countries, controlling for GDP also includes a demand dimension as more developed countries potentially host larger population shares interested in (post-material) art consumption.
#
Population size is included as an offset (see section [[id:d2d676fc-e644-4815-a06d-906a30c823f0][Analysis]]).


**** Artnews collectors
As private museums are founded by collectors, they are more likely to be founded in country-yeras where many potential founders exist.
#
While a complete measure of the art collector population is not feasible (which necessitated the choice of country-year instead of collector-year as the unit of analysis), it is still possible to construct a proxy. 
#
For this purpose I construct an indicator of the population of art collectors from the Artnews magazine collector ranking, a index published yearly since 1992 of the 200 art collectors the magazine considers most important.
#
As Artnews includes the country of residence of each collector, I construct the collector population indicator for a country-year as the number of collectors included in the Artnews ranking for that country-year (thus if no collector is included for a given country-year, the value of this index is 0). 
#
Artnews furthermore includes information on the genre(s) of each collector, which allows me to only include collectors who collect modern and contemporary art.
#
I argue that the number of Artnews collectors per country-year constitutes an indicator of the wider propensity of art collecting in a country (rather than a pool of individuals able to establish a museum) and therefore do not remove art collectors from the index after they have founded a museum (which concerns 141 collectors).



**** Density dependence
Research on organizational population parencite:&Carroll_1989_density;&Hannan_1992_dynamics has argued that foundings of organization are driven by legitimacy and competition:
#
While increasing legitimacy of a new organizational form is argued to encourage new foundings, competition is hypothesized to discourage it.
#
Both legitimacy and competition are generally derived from the number of already existing organizations, which is referred to as "density".
#
The reference has lead to the label density-dependence for this paradigm. 


# [[cite:&Bogaert_etal_2014_ecological]] only focuses on first-order effects on founding/survival, but not negative effect of second order effect
# -> just argue weaker 

However, density effects may be limited by the non-profit character of the private museum population:
# 
The traditional density dependence approach focuses on for-profit companies, where competition takes place over material inputs and or market shares.
#
As such "direct" competition is absent for private museums which are predominantly non-profits and generally operate at a loss [[parencite:&Gnyp_2015_shift]], density effects may be weaker (cite:&Bogaert_etal_2014_ecological argue this for non-profit organizational populations generally). 
# 
Nevertheless, private museums may still compete over audiences [[parencite:&Adam_2021_rise p.14]], which [[textcite:&Frey_Meier_2002_beyeler]] argues are valued both economically (through ticket prices) and symbolically (as validating exhibition choices).
# 
Furthermore, the marginal value of a private museum as an instrument of distinction might decrease as more and more founders establish their museums; in this view the symbolic capital to be gained by private museum founding constitutes a resource that is being struggled over.



Thus while the non-profit character of private museum might lead to weaker density effect sizes than in other for-profit organizational populations, it is still worth to control for.
#
I therefore include for each country-year measures based on the number of private museums open at that year, in particular a linear term (which measures legitimacy) and a squared term (which measures competition).
#
Both these operationalizations follow the density-dependence literature, and result in competition growing slowly at first, but outpacing legitimacy as the organizational population increases.
# 
Given to the transnational nature of the art field (due which legitimation and competition might not be limited to country borders) I also add global linear and squared density measures which are the same for every country in a given year and describe the number of museums open worldwide in a given year.


Another key variable of the organizational population concerns closures:
# 
While in the popular imaginary a museum might be seen as permanent, the private museum population has seen substantial closures with 71 institutions having been closed until now (cf. [[cite:&Velthuis_Gera_forthcoming_fragility]]), and growing awareness of the fragility of these institutions might in turn make their founding less attractive to founders keen of leaving a mark in history.
#
I therefore add a global variable of the number of cumulative museum closures to capture the potential delegitimating effect of the closing of institutions that often are planned as personal legacies [[parencite:&Walker_2019_collector]].[fn::While the data would allow to measure this variable also on a country-level, the fact that seven of these closures have taken place in Switzerland would turn this country into a very large outlier (the only country with more closures, the United States where 12 private museums closed, has a much larger population) which in turn would bias coefficient estimates into disproportionately reflecting the Swiss case. Using an alternative measurement of the proportion between museums opened and closed would result in a similar outlier situation for the United States and Netherlands, as these countries had seen private museum closures in the 1990s. Since the private museum population was small compared to what it would later grow towards in the 2000s and 2010s, the high closing/opening ratios for these country years would dominate the coefficient estimates. Until a more effective solution is found, I thus limit myself to a measuring the global effect of museum closures.]


**** Museum population

# *spillover*: don't know shit LUL
# *add what MOW measures*
The relations of private museum to other museums has to be considered.
#
To some extent this argument follows the density dependence argument: 
#
On the one hand, existing museums are indicative of familiarity and legitimacy in a country with museums as such, and then likely also indicate that museums are being valued, thereby possibly raising the reputational gains private collectors anticipate from founding a museum of their own, and thus the likelihood of founding one.
#
An existing museum population might also facilitate private museum founding by providing a pool of personnel with skills and contacts that can be recruited [[parencite:&Quemin_2020_power]].
#
However, existing museums may also compete with private museums for audiences, and potentially symbolic capital (for example, in countries with large public museum populations private collectors might have to invest substantial amounts to be able to achieve the level of public museums, thus discouraging all but the wealthiest private founders). 


To control for these potential influences, I use the Museums of the World database [[parencite:&deGruyter_2021_MOW]] to describe a country's art museum population. 
#
As it seems that the database has not been maintained in the last years (due to a strong decline in museum foundings being covered) I use it only to construct time-invariant indicators of the number of modern and contemporary art museums having opened until 1990.
#
In order to measure both legitimating and competitive effects, I include a linear and squared terms as in the private museum population measures.
#
For the construction of this indicator I exclude all museums that are also included in the private museum database constructed by the research team. 
# could move it to cultural spending?


*** Data processing
#
A number of countries have been excluded for various reasons:
#
The exchange rates for Zimbabwe and Venezuela were deemed unrealistic (Venezuela is discussed by [[textcite:&Blanchet_2017_conversions]]); both countries were therefore excluded.
#
Furthermore, a number of country-years have been removed for Yemen due to negative cultural spending.
#
For number of years of South Africa the wealth inequality Gini coefficient was larger than 1; in this cases it has been set to a ceiling of 0.99.
#
Finally, Iceland, the Bahamas, Monaco and Liechtenstein have been excluded as these countries' small population results in an extremely high rate of Artnews top 200 collectors per capita (and in the case of Iceland, also an extremely high rate of modern/contemporary art museums in 1990).
#
I argue that since the number of Artnews collectors is a discrete count variable, it is less suitable to provide an accurate measures in countries with small populations; the inability to measure of this variable to  accurately measure the intended concept thus justifies the exclusion of these countries on methodological grounds.




** Analytical Strategy

During data collection a number of challenges became apparent:
#
First, data coverage on some variables was substantially limited; second, the previous literature was not specific enough to derive a single precise measurement of some concepts, namely inequality and HNWIs, and third, the temporal duration of the mechanisms has not been investigated in the literature. 
#
I address these challenges as follows: 




*** Variable combinations 
#+label: fig:cpltns_vrbl_plot_v2
#+caption: Number of countries with data per year
[[file:figures/cpltns_vrbl_plot_v2.pdf]]

#
Despite substantial efforts to collect complete data for the relevant variables, it was not possible to collect data for all country-years.
#
As figure [[fig:cpltns_vrbl_plot_v2]] shows, in particular cultural spending and marginal income tax rate have coverage gaps.
#
I therefore choose an approach that attempts to (at least partly) address two competing limitations, namely omitted variable bias and data missing not-at-random:
#
Only using the most complete dataset would entail a large reduction of countries and country-years, and as dropped country-years might be missing not-at-random (i.e. there could be an association between them missing and the value that they truly have) coefficient estimates could be biased.
#
However coefficient estimates could also be biased by omitting key variables.
#
To partly remedy these shortcomings, I construct multiple datasets which vary in their inclusion of variables and country years (the more variables are included, the fewer country years can be covered).
#
In particular, I construct one dataset with all variables (1258 country years, 86 countries; referred to as "DS all IVs"), one with all variables except cultural spending (2574 country years, 153 countries; "DS --CuSp"), and one with all variables except cultural spending and marginal income tax rates (3400 country years, 163 countries; "DS --CuSp/TMITR").
#
While this approach does not solve completely either omitted variable bias (as variables with limited coverage can not be included in the datasets with more country-years) nor data missing not-at-random (still possibly present in the datasets with fewer country-years), it uses the data most effectively by including as many variables and country-years in at least one analysis, leading to a more complete picture adequate for an exploratory approach. 

#+label: fig:world_plot_faceted
#+caption: Countries colored by number of country-years per combination
[[file:figures/world_plot_faceted_v2.pdf]]

#+label: fig:cbn_cnt_line_plot
#+caption: Number of countries per year per variable combination
[[file:figures/cbn_cnt_line_plot_v2.pdf]]

Figures [[fig:world_plot_faceted]] and [[fig:cbn_cnt_line_plot]] illustrate the variation of country-year coverage between the variable combinations. 

As a consequence of the data availability of longitudinal variables, for most countries the analysis covers the years 2000-2020.
#
While such time-frame thus makes it impossible to cover the early period of private museum founding, it still allows the focus on the time period in which the majority of the foundings (~84%) have taken place.


#+latex: \begin{landscape}
#+latex: \input{./tables/tbl:descs.tex}
#+latex: \end{landscape}

# #+latex: \begin{adjustbox}{angle=90}
# #+INCLUDE: "./tables/tbl:descs.tex" export latex
# #+latex: \end{adjustbox}

*** Variable selection
While theoretical relations involving the number of HNWIs and inequality have been proposed, concrete operationalizations have been missing.
#
For the number of HNWIs, I randomly choose a threshold of 1, 5, 30, 200 million USD, while inequality is first differentiated into wealth and income inequality, for which in turn one of Gini, 10% share and 1% share is chosen randomly.
#
This choices result in 36 possible variable combinations (4 HNWI variables \times 3 income inequality variables \times 3 wealth inequality variables). 



*** Time lags
So far there has been limited investigation into the time frames each mechanism needs to take effect.
#
For example, an effect of a decrease of cultural spending might not become effective immediately as it might take time for collectors to perceive this decline and decide to act.
#
As a misspecified time lag might miss an effect that exists at a different time-lag, I take an exploratory approach and vary the lag of each longitudinal variable between one and five years.
#
To obtain comparability between the models using different time-lags, I limit the country-years to those that have data on all of the five preceding years for all time-lag variations.
# (this is the reason that coverage of the HNWI count and wealth inequality indicators increases already from 1995 onwards (figure [[fig:cpltns_vrbl_plot]]), but that the coverage of the non-control combinations increases only at 2000 (figure [[fig:cbn_cnt_line_plot]]).
#
As a complete exploration of the lag-choice space is not possible (it grows exponentially with the number of longitudinal variables included), I use an optimization procedure:
#
For a selection of variables, I first select random starting values for the lags.
#
I then select all variables in random order, and for each variable in turn vary the lag by calculating five regression models (see next section for more details) identical except for the lag of the variable in question, and keep the best fitting one (characterized by maximum log-likelihood), the lag of which is then used for the respective variables for the following models where the lag of the next variable is optimized (lags of squared variables and interactions are fixed to the lag of their main variables).
#
If multiple models fit equally well, a lag among these is selected at random.
#
These selection of variables in random order is continued until no further improvement is achieved.
#
While the random starting values and random order of variables help to explore the lag space, models can still be stuck in local optima; I therefore run each model five times, each with a different set of random starting values. 



*** Regression specification
:PROPERTIES:
:ID:       d2d676fc-e644-4815-a06d-906a30c823f0
:END:

Each regression model is specified as a negative binomial model (which is robust to potential overdispersion of the dependent variable) which is run using the xtnbreg command of Stata 14 [[parencite:&Stata_2015_xtnbreg]]. 
#
Random country intercepts are added to account for clustering of observations in countries.
#
Due to the presence of time-invariant variables (tax incentives and museum population) pure fixed effects models (which would capture only within-country variation) are not feasible, coefficients therefore describe both within-country and between-country variation.
#
I furthermore use population as an offset (which estimates founding rate per capita) to allow comparison between countries of different population sizes; all count predictors are therefore first transformed into per capita rates.
#
To facilitate convergence and interpretation, all variables except the binary variable of tax deductibility of charitable donations are also rescaled to a mean of 0 and a standard deviation of 1 (the interaction between tax deductibility of charitable donations and top marginal income tax rate and the squared terms of other variables are calculated after rescaling).
#
{{{mdlcnt_ttl}}} models are run, of which {{{cvrgd1}}} ({{{cvrgnc_rate}}}%) converge successfully. 
#
Given 36 variable combinations which are optimized five times with different starting values each per three datasets this results in an average of {{{nbr_runs_p_cbn_spec}}} regression models per variable combination.


** Results

*** Descriptive findings

Summary statistics for all variables are provided in unscaled form in table \ref{tbl:descs}.
#
A number of insights can be gained from these descriptive findings:
#
First, private museum founding is more prevalent in the smaller datasets in which countries of the Global North are disproportionately represented.
#
Consequently, the less country-years are included in a dataset, the stronger it is characterized by higher private museum founding rates (and consequently densities), higher rates of HNWIs, lower inequalities, higher GDP per capita and larger (per capita) populations of museums and collectors of modern and contemporary art.
#
For example, while in "DS all IVs" each year on average 1 private museum is founded per {{{nbr_pop_p_1pm_cbn_all}}} million inhabitants (1/{{{opng_rate_cbn1}}}), this rate is substantially lower in "DS --CuSP" and "DS -CuSp/TMITR" with 1 private museum founding per {{{nbr_pop_p_1pm_cbn_no_cult_spending}}} and {{{nbr_pop_p_1pm_cbn_no_cult_spending_and_mitr}}} million inhabitants, respectively.
#
Additionally, several variables show substantial skew (indicated by high standard deviations compared to the mean), such as the dependent variable of private museum openings (and consequently private museum density measures), as well as cultural spending, GDP and the HNWI, art museum and collector counts.
#
In particular, private museum founding is concentrated in a number of country-years:
#
Only {{{nbr_nzero_cbn_all}}} country-years see show at least one private museum founding in "DS all IVs" ({{{prop_nzero_cbn_all}}}%), while the other datasets see even lower proportions ({{{prop_nzero_cbn_no_cult_spending}}}% for "DS --CuSP" and {{{prop_nzero_cbn_no_cult_spending_and_mitr}}}% for "DS --CuSP/TMTIR", respectively).




*** general introduction :ignhead:
# #+label: plt_v62_coef_krnls
# #+caption: distribution of main coefficients
# #+attr_latex: :width 16cm
# [[file:figures/plt_v62_coef_krnls.pdf]]


# #+label: plt_v62_coef_violin
# #+caption: distribution of main coefficients
# #+attr_latex: :width 18cm
# [[file:figures/plt_v62_coef_violin.pdf]]

# #+label: fig:best_models_condensed
# #+caption: Best-fitting model per dataset
# #+attr_latex: :width 18cm
# [[file:figures/plt_v62_best_models_condensed.pdf]]

# Figure [[fig:best_models_condensed]] shows the results of the best-fitting models for each dataset (the time lags of the independent variables are omitted here, but can be seen in figure [[fig:plt_v62_reg_res_within]] in the appendix).


#+INCLUDE: "./tables/tbl:regrslts_wcptblF.tex" export latex

Table \ref{tbl:regrslts_wcptblF} displays the regression results.
#
As the estimation procedure involves the calculation of multiple models from different variable sets, table \ref{tbl:regrslts_wcptblF} displays for each variable the coefficients of the best-fitting models; the log likelihoods similarly correspond to the best-fitting model (since the coefficient variation resulting from different variable choice (e.g. the difference between the coefficients of cultural spending between a model with income inequality measured via the Gini coefficient and a model with income measured as 10% concentration) is generally not substantial, it is discussed only in the Appendix). 
# 
Coefficients can be interpreted as logged multipliers of a country's founding rate [[parencite:&Coxe_West_Aiken_2009_count]], therefore a coefficient of 0.2 corresponds to a e\textsuperscript{0.25} = 1.28 multiplier, i.e. a 28% increase in average predicted country founding rate given a 1 standard deviation change in the independent variable (the independent variables are standardized).
#
Coefficients above 0 indicate multipliers above 1, while coefficients below 0 indicate multipliers below 1.
#
Thus, coefficients of -0.5, 0.1, 0.5 and 1 correspond to 40% decrease, 10% increase, 64% increase and 171%
increase, respectively.

**** intercepts (yeet?) :ignhead:

The intercepts correspond to the predicted (logged) founding rate for a country-year with values of zero on all independent variables.
#
Given the standardization of the variables, this corresponds to a country at the means of the variables and without tax deductibility of charitable donations.
#
Thus they also illustrate the highly skewed distribution of the variables, as predicted opening count at the means for "DS all IVs" with e\textsuperscript{{{{intcpt}}}}= {{{intcpt_exp}}} is around one order of magnitude higher than average founding rate in the dataset ({{{opng_rate_cbn1}}}, cf. table \ref{tbl:descs}); a pattern of similar magnitude is present in the other datasets as well. 


**** tax incentives :ignhead:

The results for tax incentives largely support H1: 
#
Tax deductibility of donations is found to be positive and significantly related to private museum founding in "DS -CuSp/TMITR", indicating a private museum founding rate e\textsuperscript{{{{txdctblt_cbn3}}}} = {{{txdctblt_cbn3_exp}}} times higher in countries where charitable deductions are tax deductible than in countries where these donations are not tax deductible.
#
In "DS -CuSp" the interaction between top marginal income rate and tax deductibility of donations is significant, which indicates that higher top marginal income tax rate have a larger effect when charitable donations are tax deductible:
#
A 1 SD increase of the top marginal income tax rate ({{{tmitr_1SD_cbn_all}}} percentage points) increases the effect of tax deductibility of donations by a factor of e\textsuperscript{{{{txdctblt_tmitr_interact_cbn2}}}} = {{{txdctblt_tmitr_interact_cbn2_exp}}}.
#
In "DS all IVs", the interaction is still positive, but no longer significant, presumably since "DS all IVs" is primarily composed of countries in which charitable donations are tax deductible (table \ref{tbl:descs}) and hence little variation exists.
#
Thus despite significant effects not being present in every dataset, the data overall indicates substantial support for an association between tax incentives and private museum founding (H1). 


**** cultural spending :ignhead:


Government cultural spending is found to have a significant inverse-U shaped association with private museum founding.
#
While at lower values the association is positive, the effect decreases at higher levels and eventually turns negative.
#
In particular, up to a value of {{{smorc_lin_flipped}}}/(2*{{{smorc_sqrd}}}) = {{{smorc_top_point_std}}} (on the standardized government spending variable, which corresponds to cultural spending of {{{smorc_top_point}}} USD per capita, approximately the 2020 government cultural spending of Slovakia ({{{smorc_2020_SVK}}} USD), the United Arab Emirates ({{{smorc_2020_ARE}}} USD) or New Zealand ({{{smorc_2020_NZL}}} USD)) an increase in government spending corresponds to a higher predicted likelihood of private museum founding. 
#
This range of a positive association between government spending and private museum founding consists of {{{smorctop_below_CYs_cnt}}} ({{{smorctop_below_CYs_prop}}}%) of the country-years belonging to "DS all IVs"; it also contains {{{smorctop_below_nbr_opened_prop}}}% of covered private museum foundings.
#
It is furthermore worth to consider that "DS all IVs" consists disproportionately of developed countries, the true proportion of country-years in which higher government expenditure is associated with higher private museum is likely even higher.
#
Nevertheless, in the range above this turning point which (in 2020) includes countries prominent for their private museum populations such as Germany ({{{smorc_2020_DEU}}} USD), France ({{{smorc_2020_FRA}}} USD), the Nethelands ({{{smorc_2020_NLD}}} USD) or Switzerland ({{{smorc_2020_CHE}}} USD) increases in government spending are associated with lower rates of private museum founding (and conversely, decreases in government spending with higher rates of private museum founding).
# 
The data thus supports both the the crowding-out argument of the private museum literature which considers private museum founding  a consequence of declining government spending (H2) as well as the crowding in argument raised by philanthropy scholars. 
#
However, little evidence is found for a lack of government spending facilitating private museum founding in countries  with emerging art scenes, as these are located in the range in which government spending is positively associated with private museum founding. 

**** inequality :ignhead:


The association between inequality variables and private museum founding is mixed.
#
While wealth inequality variables are positively and significantly associated with the establishment of new private museums, income inequality is significantly associated with lower founding. 
#
For example, a 1 SD increase of the wealth share of the top 10% (7.6% in 2020 in "DS all IVs", which corresponds approximately to the difference between Denmark (50.2%) and the Czech Republic (57.9) in 2020, or to the longitudinal change in the United States from 1991 (64.1%) to 2011 (71.7%)) corresponds to an increase in private museum founding rate by a factor of exp(0.28) = 1.32.


#
Conversely, a 1 SD decrease of the income share of the top 10% (8.9% in 2020 in "DS all IVs", which corresponds approximately to the difference between Sweden (30.8%) and Canada (39.7)) is associated with a decrease in private museum founding rate by a factor of exp(-0.39) = 0.68.
# 
Furthermore, Effects are smaller in "DS all IVs" than in the other datasets, which leads to the gini coefficients not being significant.
#


**** HNWI :ignhead:




Finally, the effect of HNWIs (H4) is mostly negative and relatively small in the two larger datasets, but evenly centered around 0 in "DS all IVs". 


# Overall, cbn_no_cult_spending and cbn_no_cult_spending_and_mitr are more similar in coefficient results than either is to cbn_all. 
# #
# This can be seen in the identical selection of variables for HNWI and inequality as well as similar coefficient signs, sizes and significances:
# #



# *** HNWIs (H4)

# The coefficients are positive in the "cbn_no_cult_spending" and "cbn_no_cult_spending_and_mitr", but they are small and insignificant, thus lending no support to H4, as does the coefficient in "cbn_all", which is virtually indistinguishable from 0.
# #
# Thus there is little support for the hypothesis that the private museum founding is associated with an increasing number of super-rich.




# *** Controls 

# **** GDP and population size

# The controls for GDP per capita and population size are positive and significant in cbn_no_cult_spending and cbn_no_cult_spending_and_mitr, but become marginally significant in cbn_all.
# #
# As these are rather crude measures, them becoming insignificant could indicate again a strong influence of cultural spending, or different effects being present in the different datasets.


# **** density dependence 
# In all datasets, cumulative openings (legitimacy) and cumulative openings squared (competition) correspond to the density-dependence hypotheses, namely a positive effect of legitimacy and a negative of competition; however legitimacy is only significant in the "all variables" dataset, and competition only in "all variables" and "all variables except cultural spending".


# **** Artnews collector ranking 
# Suprisingly, the number of collectors in the Artnews collector ranking has a negative effect on private museum founding, which is significant in cbn_all and marginally significant elsewhere.
# #
# At the moment I do not have a plausible interpretation, but it could be an artifact of still including collectors with a private museum in the computation of the variable.






# # Figure [[fig:reg_within_tmitr_fixed]] shows one way of evaluating the results (while all inequality and HNWI variables are included in the figure, only one per group is included in each model).




# # While figure [[fig:reg_within_tmitr_fixed]] already allows to assess coefficient size and significance, the impact of the variables and lags to model fit has not been fully evaluated yet.
# # # 
# # While substantial model fit variation exists between combinations (figure [[fig:cbn_log_likelihoods]]), this is expected as combinations differ in size and variables.
# # #
# # Figure [[fig:mdl_fit_plot]] shows the average changes in log-likelihood resulting from different lag choices, which paint a picture similar to figure [[fig:reg_within_tmitr_fixed]] as larger coefficients are associated with larger model improvements (especially in the inequality variables).
# # #
# # A selection of the best-fitting models (figure [[fig:best_models_tmitr_fixed]]) also shows that lagged indicators are often chosen (the necessity for further data cleaning is especially visible in the exclusive choice of 1 billion as the HNWI cutoff, which as in figure [[fig:reg_within_tmitr_fixed]] is likely an artifact, but here results in the complete exclusion of other HNWI thresholds).



** Discussion and conclusion
#

The previous exploratory analysis shows mixed results:
# #
# While moderate support can be found for a positive effect of tax incentives, effects for inequality are too divergent to allow clear conclusions.
While moderate support can be found for a positive effect of tax deductibility of donations, the effect of tax exemption for non-profits is negative.
#
Given that tax-exemption for non-profits exhibit only very little variance, its negative effect might be more due to multi-variate outliers or other regression particularities.
#

# Furthermore, while government funding has a significant effect, it is positive and thus contradicting the argument in the private museum literature (yet supporting the signaling theory of government spending from philanthropy literature).
# # 
# Finally, no support is found for elite wealth.


These findings first and foremost point to the need of theoretical development in particular in regards to the effects of inequality as well as the role of government spending.
#
Furthermore, additional work is necessary in the measurement of some of the concepts.
#
Despite such limitations, this exploratory research constitutes a substantial contribution to the studies of private museums, and opens the ground for further systematic studies into the dynamics of this new organizational population.


*** limitations :ignhead:

# Furthermore, given that the magazine has for all years collected the top 200 collectors and therefore cannot capture changes in the total art collector population, the constructed indicator measures the relative propensity of art collecting compared to other countries/time periods.


The current study is limited by a number of factors:
#
As interest in the organizational form of private museums has risen only recently, data collection has been both retrospective (which might be less inclusive than continuous measurements based on for example industry directories) and primarily based on english-language media.
#
Furthermore, private museums are here treated as uniform, yet as they have been shown to exhibit substantial variation cite:&LarrysList_2015_report, different kinds of private museum might be subject to different social forces (yet more detailed analysis could also complicate the analysis as already in the current datasets where all private museums are pooled the founding of one constitutes a relatively rare event which most countries don't experience even once).
#
Also, multiple predictors are exhibiting substantial limitations in measuring their intended concepts, such as the tax incentives and non-private art museum populations variables (which are only cross-sectional and in the former case not art-sector specific), the WID HNWI data (which make aggregation beyond 200m USD infeasible) and the collector data (which does not capture absolute changes collector populations).
#
Furthermore substantial gaps in data coverage of cultural spending (which might also be affected by limited standardization) and top marginal income tax rates has so far necessitated the use of multiple datasets (and given that the former is reported by national statistical agencies, it is unlikely that the present country-year gaps are will filled in the foreseeable future).
#
A potentially influential phenomenon which might influence private museum founding, the exchange of ideas between art collectors, is completely unobservable on a systematic level. 
#
Finally, further relationships between variables (such as mediation or moderation) as well as nonlinear relationships to private museum foundings might be present which if not taken into account might bias coefficient estimates. 



Nevertheless, *some more about contributions*

  
** References
# \hypertarget{refs}{}

#+Latex: \begin{sloppypar}
#+Latex: \printbibliography
#+Latex: \end{sloppypar}



* appendix

#+label: fig:plt_v62_reg_res_within
#+caption: Coefficients of the 3 best-fittin models per lag and variable combination, lines indicate stability of other variables as the lag of the variable on the line is varied, minor variation around x-axis added to improve legibility
[[file:figures/plt_v62_reg_res_within.pdf]]
