#+latex_class: elsarticle
# erases make title
# #+BIND: org-export-latex-title-command ""


# fucks all the maketitlestuff just to be sure
#+OPTIONS: num:nil
#+OPTIONS: toc:nil
#+OPTIONS: h:5

#+BEGIN_SRC R :session calc :exports none :results values drawer :dir /home/johannes/Dropbox/
dt_nbrs <- fread("/home/johannes/Dropbox/phd/papers/org_pop/misc/tbl_nbrs_v34.csv")

dt_nbrs[, .(macro_str = sprintf("#+MACRO: %s %s", nbr_name, nbr_fmt)), grp] %>%
  .[, .(grp_str = paste(macro_str, collapse = "\n")), grp] %>%
  .[, .(grp_str2 = paste0("# ", grp, "\n", grp_str))] %>% 
  .[, paste0(grp_str2, collapse = "\n\n\n")]
  
#+END_SRC

#+RESULTS:
:results:
# pmdb_stats
#+MACRO: nbr_muem_in_pmdb 547
#+MACRO: nbr_opnd_wld 516
#+MACRO: nbr_clsd_wld 101
#+MACRO: nbr_cry_wal1pm_all 64
#+MACRO: nbr_pm_openatm 446
#+MACRO: nbr_opnd_snc2k 420
#+MACRO: perc_opnd_snc2k 76.8%


# nbr_pm_regsub
#+MACRO: regsub_cnt_Western_Europe 136
#+MACRO: regsub_cnt_Eastern_Asia 97
#+MACRO: regsub_cnt_Northern_America 77
#+MACRO: regsub_cnt_Southern_Europe 71
#+MACRO: regsub_cnt_Northern_Europe 27


# cbn_info
#+MACRO: nbr_cy_cbn1 1241
#+MACRO: nbr_cy_cbn2 2474
#+MACRO: nbr_cy_cbn3 3148
#+MACRO: nbr_crys_cbn1 85
#+MACRO: nbr_crys_cbn2 147
#+MACRO: nbr_crys_cbn3 156
#+MACRO: nbr_opngs_cbn1 355
#+MACRO: nbr_opngs_cbn2 402
#+MACRO: nbr_opngs_cbn3 403
#+MACRO: prop_opngs_cvrd_cbn1 0.649
#+MACRO: prop_opngs_cvrd_cbn2 0.735
#+MACRO: prop_opngs_cvrd_cbn3 0.737
#+MACRO: perc_opngs_cvrd_cbn1 64.9%
#+MACRO: perc_opngs_cvrd_cbn2 73.5%
#+MACRO: perc_opngs_cvrd_cbn3 73.7%


# opng_rates_fmt
#+MACRO: opng_rate_cbn1 0.0112
#+MACRO: opng_rate_cbn2 0.0061
#+MACRO: opng_rate_cbn3 0.0049


# opng_prop_vlus
#+MACRO: nbr_zero_cbn1 1 030
#+MACRO: nbr_nzero_cbn1 211
#+MACRO: prop_nzero_cbn1 17.0
#+MACRO: nbr_zero_cbn2 2 222
#+MACRO: nbr_nzero_cbn2 252
#+MACRO: prop_nzero_cbn2 10.2
#+MACRO: nbr_zero_cbn3 2 895
#+MACRO: nbr_nzero_cbn3 253
#+MACRO: prop_nzero_cbn3 8.0
#+MACRO: nbr_zero_cbn_controls 5 845
#+MACRO: nbr_nzero_cbn_controls 298
#+MACRO: prop_nzero_cbn_controls 4.9


# popnbrs_p1pm
#+MACRO: nbr_pop_p_1pm_cbn1 89.5
#+MACRO: nbr_pop_p_1pm_cbn2 163
#+MACRO: nbr_pop_p_1pm_cbn3 205
#+MACRO: nbr_pop_p_1pm_cbn_controls 83.1


# cvrgnc
#+MACRO: cvrgd1 254 251
#+MACRO: cvrgd0 3 269
#+MACRO: mdlcnt_ttl 257 520
#+MACRO: cvrgnc_rate 98.7
#+MACRO: nbr_runs_p_cbn_spec 596


# velp_minmax
#+MACRO: velp_cryname_min Hungary
#+MACRO: velp_cryname_max Portugal
#+MACRO: velp_year_scld_min -0.116
#+MACRO: velp_year_scld_max 0.063
#+MACRO: velp_year_pct_min 1.6
#+MACRO: velp_year_pct_max 0.9


# rate_opng_glbl
#+MACRO: rate_opng_glbl_cbn1 0.00430
#+MACRO: rate_opng_glbl_cbn2 0.00298
#+MACRO: rate_opng_glbl_cbn3 0.00283
#+MACRO: rate_opng_glbl_cbn_controls 0.00229


# rate_opng_glbl_yearly
#+MACRO: rate_opng_glbl_yearly_cbn1 0.00404
#+MACRO: rate_opng_glbl_yearly_cbn2 0.00288
#+MACRO: rate_opng_glbl_yearly_cbn3 0.00274
#+MACRO: rate_opng_glbl_yearly_cbn_controls 0.00221


# opng_p1m_glbl_yearly
#+MACRO: opng_p1m_glbl_yearly_cbn1 248
#+MACRO: opng_p1m_glbl_yearly_cbn2 347
#+MACRO: opng_p1m_glbl_yearly_cbn3 365
#+MACRO: opng_p1m_glbl_yearly_cbn_controls 452


# velp_mean
#+MACRO: velp_mean_uscld -0.009
#+MACRO: velp_quantl25_uscld -0.024
#+MACRO: velp_quantl75_uscld 0.007
#+MACRO: velp_mean_scld 0.13
#+MACRO: velp_quantl25_scld 0.34
#+MACRO: velp_quantl75_scld 0.10


# hief
#+MACRO: cor_hief_eth2k 0.84
#+MACRO: hief_prop_within 7.4
#+MACRO: hief_nbr_cry_imputed 35


# intcpt_info
#+MACRO: intcpt -4.67
#+MACRO: intcpt_exp 0.009


# txinctvs
#+MACRO: Ind_tax_incentives_cbn3_coef 0.91
#+MACRO: Ind_tax_incentives_cbn3_coef_exp 2.5
#+MACRO: Ind_tax_incentives_cbn3_pvlu 0.06
#+MACRO: ti_tmitr_interact_cbn2_pvlu 0.10
#+MACRO: Ind_tax_incentives_cbn2_coef 0.57
#+MACRO: tmitr_approx_linear20step_cbn2_coef -0.28
#+MACRO: ti_tmitr_interact_cbn2_coef 0.70
#+MACRO: ti_tmitr_interact_cbn2_coef_exp 2.02
#+MACRO: tmitr_1SD_cbn2 13.4
#+MACRO: tmitr_neteffct_txdctblt1_cbn2 0.43
#+MACRO: tmitr_neteffct_txdctblt1_cbn2_exp 1.53
#+MACRO: tmitr_iso3c1 50
#+MACRO: tmitr_iso3c2 36


# smorc_stats
#+MACRO: smorc_lin 0.65
#+MACRO: smorc_lin_flipped -0.65
#+MACRO: smorc_sqrd -0.64
#+MACRO: smorc_top_point_std 0.51
#+MACRO: smorc_top_point 501


# smorc_vlus_2020
#+MACRO: smorc_2020_SVK 415
#+MACRO: smorc_2020_NZL 462
#+MACRO: smorc_2020_POL 466
#+MACRO: smorc_2020_LVA 468
#+MACRO: smorc_2020_AUS 500
#+MACRO: smorc_2020_ESP 501
#+MACRO: smorc_2020_CAN 513
#+MACRO: smorc_2020_HRV 521
#+MACRO: smorc_2020_IRL 529
#+MACRO: smorc_2020_SGP 541
#+MACRO: smorc_2020_LTU 584
#+MACRO: smorc_2020_MLT 589
#+MACRO: smorc_2020_SVN 595
#+MACRO: smorc_2020_DEU 661
#+MACRO: smorc_2020_FRA 678
#+MACRO: smorc_2020_BEL 689
#+MACRO: smorc_2020_AUT 694
#+MACRO: smorc_2020_NLD 782
#+MACRO: smorc_2020_FIN 799
#+MACRO: smorc_2020_CHE 806
#+MACRO: smorc_2020_EST 820
#+MACRO: smorc_2020_SWE 859
#+MACRO: smorc_2020_DNK 1 058
#+MACRO: smorc_2020_HUN 1 410
#+MACRO: smorc_2020_NOR 1 544
#+MACRO: smorc_2020_LUX 1 563


# smorc_top_point_stats
#+MACRO: smorctop_below_CYs_cnt 891
#+MACRO: smorctop_above_CYs_cnt 350
#+MACRO: smorctop_below_nbr_opened_cnt 240
#+MACRO: smorctop_above_nbr_opened_cnt 115
#+MACRO: smorctop_below_CYs_prop 71.8
#+MACRO: smorctop_above_CYs_prop 28.2
#+MACRO: smorctop_below_nbr_opened_prop 67.6
#+MACRO: smorctop_above_nbr_opened_prop 32.4


# shweal_stats
#+MACRO: shweal_1SD_cbn1 7.5
#+MACRO: shweal_iso3c1 50.2
#+MACRO: shweal_iso3c2 57.9
#+MACRO: shweal_lngtd_vlu_year1 64.1
#+MACRO: shweal_lngtd_vlu_year2 71.7
#+MACRO: shweal_cbn1 0.35
#+MACRO: shweal_cbn1_exp 1.42
#+MACRO: shweal_lngtd_year1 1991
#+MACRO: shweal_lngtd_year2 2011


# sptinc_stats
#+MACRO: sptinc_1SD_cbn1 8.9
#+MACRO: sptinc_iso3c1 30.8
#+MACRO: sptinc_iso3c2 39.7
#+MACRO: sptinc_lngtd_vlu_year1 34.8
#+MACRO: sptinc_lngtd_vlu_year2 43.5
#+MACRO: sptinc_cbn1 -0.39
#+MACRO: sptinc_cbn1_exp 0.67
#+MACRO: sptinc_lngtd_year1 2010
#+MACRO: sptinc_lngtd_year2 2017


# dens_coef_stats
#+MACRO: pm_density_cbn1 1.30
#+MACRO: pm_density_sqrd_cbn1 -0.30
#+MACRO: pm_density_glbl_cbn1 -0.29
#+MACRO: pm_density_glbl_sqrd_cbn1 -0.20
#+MACRO: dens_cry_top_point_std_cbn1 2.17
#+MACRO: dens_glbl_top_point_std_cbn1 -0.72
#+MACRO: dens_cry_top_point_cbn1 0.77
#+MACRO: dens_glbl_top_point_cbn1 217.83


# dens_cry_top_point_stats
#+MACRO: dens_cry_top_below_CYs_cnt 1 168
#+MACRO: dens_cry_top_above_CYs_cnt 73
#+MACRO: dens_cry_top_below_nbr_opened_cnt 315
#+MACRO: dens_cry_top_above_nbr_opened_cnt 40
#+MACRO: dens_cry_top_below_CYs_prop 94.1
#+MACRO: dens_cry_top_above_CYs_prop 5.9
#+MACRO: dens_cry_top_below_nbr_opened_prop 88.7
#+MACRO: dens_cry_top_above_nbr_opened_prop 11.3


# dens_glbl_top_point_stats
#+MACRO: dens_glbl_top_above_CYs_cnt 894
#+MACRO: dens_glbl_top_below_CYs_cnt 347
#+MACRO: dens_glbl_top_above_nbr_opened_cnt 261
#+MACRO: dens_glbl_top_below_nbr_opened_cnt 94
#+MACRO: dens_glbl_top_above_CYs_prop 72.0
#+MACRO: dens_glbl_top_below_CYs_prop 28.0
#+MACRO: dens_glbl_top_above_nbr_opened_prop 73.5
#+MACRO: dens_glbl_top_below_nbr_opened_prop 26.5


# gdp_stats
#+MACRO: gdp_coef_cbn3 0.74
#+MACRO: gdp_coef_cbn2 0.61
#+MACRO: gdp_coef_cbn1 0.11
#+MACRO: gdp_1SD_cbn1 24.93
#+MACRO: gdp_1SD_cbn2 21.22
#+MACRO: gdp_1SD_cbn3 19.78


# hnwi_stats
#+MACRO: hnwi_nbr_5M_cbn2_coef -0.23
#+MACRO: hnwi_nbr_5M_cbn2_pvlu 0.042
#+MACRO: hnwi_nbr_5M_cbn3_coef -0.19
#+MACRO: hnwi_nbr_5M_cbn3_pvlu 0.056


# pltcfgs
#+MACRO: ynkplt_cbn_log_likelihoods (eval (concat "#+label: fig:cbn_log_likelihoods\n" "#+caption: model log likelihood distribution per dataset\n" "#+attr_latex: :width 16cm\n" "[[file:figures/plt_v34_cbn_log_likelihoods.pdf]]"))
#+MACRO: ynkplt_cvrgnc (eval (concat "#+label: fig:cvrgnc\n" "#+caption: Model improvement\n" "#+attr_latex: :width 12cm\n" "[[file:figures/plt_v34_cvrgnc.pdf]]"))
#+MACRO: ynkplt_coef_violin (eval (concat "#+label: fig:coef_violin\n" "#+caption: Distribution of coefficient point estimates (Gaussian kernel density estimate; bandwidth = 0.04)\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v34_coef_violin.pdf]]"))
#+MACRO: ynkplt_best_coefs_cloud (eval (concat "#+label: fig:best_coefs_cloud\n" "#+caption: Coefficient point estimate and 95% CI\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v34_best_coefs_cloud.pdf]]"))
#+MACRO: ynkplt_best_coefs_single (eval (concat "#+label: fig:best_coefs_single\n" "#+caption: Model coefficients (best fitting model)\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v34_best_coefs_single.pdf]]"))
#+MACRO: ynkplt_best_coefs_single_cbn1 (eval (concat "#+label: fig:best_coefs_single_cbn1\n" "#+caption: asdf\n" "#+attr_latex: :width 14cm\n" "[[file:figures/plt_v34_best_coefs_single_cbn1.pdf]]"))
#+MACRO: ynkplt_lag_dens (eval (concat "#+label: fig:lag_dens\n" "#+caption: Lag choice distribution\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v34_lag_dens.pdf]]"))
#+MACRO: ynkplt_oneout_coefs (eval (concat "#+label: fig:oneout_coefs\n" "#+caption: Model coefficients (best fitting model; colored by significance of model improvement)\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v34_oneout_coefs.pdf]]"))
#+MACRO: ynkplt_oneout_llrt_lldiff (eval (concat "#+label: fig:oneout_llrt_lldiff\n" "#+caption: Model improvement given variable inclusion (Gaussian kernel density estimate; bandwidth = 0.4)\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v34_oneout_llrt_lldiff.pdf]]"))
#+MACRO: ynkplt_oneout_llrt_z (eval (concat "#+label: fig:oneout_llrt_z\n" "#+caption: Distribution of Z-score of log-likelihood ratio test p-value (Gaussian kernel density estimate; bandwidth = 0.1)\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v34_oneout_llrt_z.pdf]]"))
#+MACRO: ynkplt_vrbl_cycnt (eval (concat "#+label: fig:vrbl_cycnt\n" "#+caption: Number of countries with per year per variable\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v34_vrbl_cycnt.pdf]]"))
#+MACRO: ynkplt_cbn_cycnt (eval (concat "#+label: fig:cbn_cycnt\n" "#+caption: Number of countries per year per variable combination\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v34_cbn_cycnt.pdf]]"))
#+MACRO: ynkplt_vif (eval (concat "#+label: fig:vif\n" "#+caption: Distribution of VIF estimates (Gaussian kernel density estimate; bandwidth = 0.1)\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v34_vif.pdf]]"))
#+MACRO: ynkplt_velp (eval (concat "#+label: fig:velp\n" "#+caption: Results of regressing longitudinal variables on year\n" "#+attr_latex: :width 24cm\n" "[[file:figures/plt_v34_velp.pdf]]"))
#+MACRO: ynkplt_cntrfctl (eval (concat "#+label: fig:cntrfctl\n" "#+caption: Counterfactual simulations\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v34_cntrfctl.pdf]]"))
#+MACRO: ynkplt_pred_taxinc (eval (concat "#+label: fig:pred_taxinc\n" "#+caption: Tax Incentives and Private Museum Founding: Adjusted Predictions at the Means (DS all IVs; population 100 mil.; 95% CI)\n" "#+attr_latex: :width 14cm\n" "[[file:figures/plt_v34_pred_taxinc.pdf]]"))
#+MACRO: ynkplt_pred_smorc (eval (concat "#+label: fig:pred_smorc\n" "#+caption: Goverment Cultural Spending and Private Museum Founding: Adjusted Predictions at the Means (population 100 mil.; 95% CI)\n" "#+attr_latex: :width 14cm\n" "[[file:figures/plt_v34_pred_smorc.pdf]]"))
#+MACRO: ynkplt_pred_ptinc (eval (concat "#+label: fig:pred_ptinc\n" "#+caption: ptinc\n" "#+attr_latex: :width 14cm\n" "[[file:figures/plt_v34_pred_ptinc.pdf]]"))
#+MACRO: ynkplt_pred_hweal (eval (concat "#+label: fig:pred_hweal\n" "#+caption: hweal\n" "#+attr_latex: :width 14cm\n" "[[file:figures/plt_v34_pred_hweal.pdf]]"))
#+MACRO: ynkplt_pred_hnwi (eval (concat "#+label: fig:pred_hnwi\n" "#+caption: hweal\n" "#+attr_latex: :width 18cm\n" "[[file:figures/plt_v34_pred_hnwi.pdf]]"))
#+MACRO: ynkplt_oucoefchng (eval (concat "#+label: fig:oucoefchng\n" "#+caption: Coefficient changes given addition of other variables\n" "#+attr_latex: :width 24cm\n" "[[file:figures/plt_v34_oucoefchng.pdf]]"))
#+MACRO: ynkplt_pred_smorc4way (eval (concat "#+label: fig:pred_smorc4way\n" "#+caption: asdf\n" "#+attr_latex: :width 17cm\n" "[[file:figures/plt_v34_pred_smorc4way.pdf]]"))


# figlbls
#+MACRO: rplt_cbn_log_likelihoods \ref{fig:cbn_log_likelihoods}
#+MACRO: rplt_reg_res_within \ref{fig:reg_res_within}
#+MACRO: rplt_reg_res_all \ref{fig:reg_res_all}
#+MACRO: rplt_best_models_wlag \ref{fig:best_models_wlag}
#+MACRO: rplt_best_models_condensed \ref{fig:best_models_condensed}
#+MACRO: rplt_lag_cprn \ref{fig:lag_cprn}
#+MACRO: rplt_cvrgnc \ref{fig:cvrgnc}
#+MACRO: rplt_coef_violin \ref{fig:coef_violin}
#+MACRO: rplt_best_coefs_cloud \ref{fig:best_coefs_cloud}
#+MACRO: rplt_best_coefs_single \ref{fig:best_coefs_single}
#+MACRO: rplt_best_coefs_single_cbn1 \ref{fig:best_coefs_single_cbn1}
#+MACRO: rplt_lag_dens \ref{fig:lag_dens}
#+MACRO: rplt_oneout_coefs \ref{fig:oneout_coefs}
#+MACRO: rplt_oneout_llrt_lldiff \ref{fig:oneout_llrt_lldiff}
#+MACRO: rplt_oneout_llrt_z \ref{fig:oneout_llrt_z}
#+MACRO: rplt_vrbl_cycnt \ref{fig:vrbl_cycnt}
#+MACRO: rplt_cbn_cycnt \ref{fig:cbn_cycnt}
#+MACRO: rplt_vif \ref{fig:vif}
#+MACRO: rplt_velp \ref{fig:velp}
#+MACRO: rplt_cntrfctl \ref{fig:cntrfctl}
#+MACRO: rplt_pred_taxinc \ref{fig:pred_taxinc}
#+MACRO: rplt_pred_smorc \ref{fig:pred_smorc}
#+MACRO: rplt_pred_ptinc \ref{fig:pred_ptinc}
#+MACRO: rplt_pred_hweal \ref{fig:pred_hweal}
#+MACRO: rplt_pred_hnwi \ref{fig:pred_hnwi}
#+MACRO: rplt_oucoefchng \ref{fig:oucoefchng}
#+MACRO: rplt_oucoefchng_tile \ref{fig:oucoefchng_tile}
#+MACRO: rplt_oucoefchng_cbn1 \ref{fig:oucoefchng_cbn1}
#+MACRO: rplt_oucoefchng_cbn2 \ref{fig:oucoefchng_cbn2}
#+MACRO: rplt_oucoefchng_cbn3 \ref{fig:oucoefchng_cbn3}
#+MACRO: rplt_pred_smorc4way \ref{fig:pred_smorc4way}


# tbllbls
#+MACRO: rtbl_regrslts_wcptblF \ref{tbl:regrslts_wcptblF}
#+MACRO: rtbl_regrslts_wcptblT \ref{tbl:regrslts_wcptblT}
#+MACRO: rtbl_descs \ref{tbl:descs}
#+MACRO: rtbl_cbn_cpsgn \ref{tbl:cbn_cpsgn}
:end:

#+LATEX_HEADER: \begin{filecontents}{refs_sup.bib}
#+LATEX_HEADER: \input{sup_materials.bib}
#+LATEX_HEADER: \end{filecontents}



* Supplementary online materials 

#+latex: \appendix
#+latex: \setcounter{page}{1}


# #+latex: \setcounter{table}{0}
# #+latex: \renewcommand{\thetable}{A\arabic{table}}
# #+latex: \setcounter{figure}{0}
# #+latex: \renewcommand{\thefigure}{A\arabic{figure}}

#+latex: \counterwithin{table}{subsection}
#+latex: \counterwithin{figure}{subsection}
#+latex: \renewcommand{\thesubsection}{\Alph{subsection}}



** Data Coverage
:PROPERTIES:
:ID:       9092cd69-4ad9-49b7-98c0-38c878fc93d7
:CUSTOM_ID: app_data_coverage
:END:
# #+label: fig:openings
# #+caption: Private Museum openings (absolute and population-rate) of 12 countries with highest counts. 
# [[file:figures/foundings_country_cnt_and_rate.pdf]]

# #+label: fig:cpltns_vrbl_plot_v2
# #+caption: Number of countries with data per year
# [[file:figures/cpltns_vrbl_plot_v2.pdf]]


{{{ynkplt_vrbl_cycnt}}}



{{{ynkplt_cbn_cycnt}}}



Figure {{{rplt_vrbl_cycnt}}} shows the country-year coverage of the main variables (other HNWI thresholds and inequality shares follow the ones depicted).
#
In particular it can be seen that the coverage of wealth variables in the WID improves substantially from 1995 onwards, a pattern that is to a lesser extent also visible in indicators of cultural spending and top marginal income tax rates.
#
Given this state of data coverage and the fact that five years of subsequent data are required for lag length optimization, the observation period for the largest proportion of countries starts in the year 2000 or later  (figure {{{rplt_cbn_cycnt}}}, the start 1995 is set by the availability of Artnews collector ranking data from 1990 onwards).
#


# #+label: fig:world_plot_faceted
# #+caption: Countries colored by number of country-years per combination
# [[file:figures/world_plot_faceted_v2.pdf]]


# Figures [[fig:world_plot_faceted]] and [[fig:cbn_cnt_line_plot]] illustrate the variation of country-year coverage between the variable combinations. 

# As a consequence of the data availability of longitudinal variables, for most countries the analysis covers the years 2000-2020.


# ** Combination composition
# :PROPERTIES:
# :ID:       b758316a-6acb-446a-870b-9177b54571ba
# :CUSTOM_ID: app_cbncpsgn
# :END:

# # #+INCLUDE: "./tables/tbl:cbn_cpsgn_v27.tex" export latex


# Table {{{rtbl_cbn_cpsgn}}} shows the coverage of datasets by region. 
# #
# Relative between-dataset differences are particularly strong for Africa, Latin America and Europe.
# # FIXME: numbers that are not org-macros
# While Europe with more than half of the country-years is "DS all IVs" constitutes the largest region (indicating that European countries report relatively detailed statistics on government spending), its share declines to 27.9% and 23% in "DS -CuSp" and "DS -CuSp/TMITR", respectively.
# #
# Conversely, Africa and Latin America claim larger shares in the larger datasets, with the former becoming the region contributing the largest nubmer of country years (1088 or 32.1%) in "DS -CuSp/TMITR".
# #
# The proportion of North America and Oceania also declines in larger datasets, but this results in comparatively less changes in dataset composition as these regions consist of relatively few countries. 





** Data processing
:PROPERTIES:
:ID:       eef6b3c3-fe92-46fb-a308-00aabeb70d7a
:CUSTOM_ID: app_data_processing
:END:

*** Cultural spending data source combination

This combination of multiple data sources requires the harmonization of different reporting standards: 
#
Whereas the the IMF and Eurostat report data exclusively as "Total government expenditure" (TLYCG), the UN uses "Final consumption expenditure" (P3CG); the OECD reports data in both formats ("Total government expenditure" is calculated from "Final consumption expenditure" as well as a number of other items, such as compensation of employees and subsidies). 
#
Moreoever, within each format minor variations exist between data sources, the data for a country-year is thus chosen in order of OECD followed by UN for P3CG, and OECD followed by IMF followed by Eurostat for TLYCG.
# (for the UN data, sometimes data is also reported in multiple Series corresponding to different SNA methodologies (see [[textcite:&UN_2022_consumption]] footnote 2 for details); here SNA 2008 methodology is chosen if available, otherwise the mean of the other series is taken).


As the overall goal is to create a complete picture of government expenditure, Total government expenditure is estimated from Final consumption expenditure for country-years where data is only available for the latter.
# based on the years in which the series overlap
For countries where TLYCG and P3CG series have some overlap and years exist with P3CG data but not TLYCG data, a country-specific scaler to convert P3CG to TLYCG is constructed from overlapping years, which is then used to impute TLYCG for the years in which only P3CG data is available.
#
For countries with only P3CG data, the average ratio of all country-years with both P3CG and TLYCG data is chosen to impute TLYCG (as on average P3CG is 58% of TLYCG, the average scaler is 1/0.58 = 1.72). 
#
Amounts are reported in current local currency units and converted to 2021 USD using price indices and purchasing power parity adjusted exchange rates from the World Inequality Database (WID,  [[citeyear:&WID_2021_WID]]).
#
 

# [fn::An alternative would be to use purchasing power parity exchange rates, which reflect local price levels (as [[textcite:&Blanchet_2017_conversions]] argues, 1 euro or 7 yuan allow the purchase of the same amount of oil on international markets, but different amounts of food in Beijing or Paris). As the art market is however substantially transnational [[parencite:&Velthuis_Curioni_2015_canvases]], and discussion of government spending heavily revolves around acquisition budgets (which are dedicated to the purchase of artworks that often are  international), I consider market exchange rates more appropriate.]

*** Social Fragmentation
The Historical Index of Ethnic Fractionalization (HIEF, cite:&Drazanova_2020_HIEF), as well as the underlying Composition of Religious and Ethnic Groups Project [[citep:&CREG_2012_whitepaper]] provides data coverage only until 2013.
#
However, as ethnic group percentages change slowly within countries (only {{{hief_prop_within}}}% of variation from 1995 to 2013 is within-country variation, the remainder being between-country variation), I consider it appropriate to fill up values from 2014 to 2020 by carrying over the 2013 value to be able to include the as many country-years as possible.
#
Furthermore, for {{{hief_nbr_cry_imputed}}} countries for which the HIEF dataset is not available, I impute it based on the (more complete) variable "Ethnic Fractionalization in the year 2000" [[citep:&Alesina_etal_2003_fractionalization]], as both variables are strongly correlated (r={{{cor_hief_eth2k}}}).



*** Imputation

Due to the exploratory approach of testing variables at lag lengths varying from one to five years, missing values can potentially substantially limit the number of country years as a single missing value leads to the exclusion of the next five years.
#
To avoid such loss of data, missing values in the country year time series which are parts of gaps of up to three years are linearly imputed.
#
This primarily concerns government cultural spending (25 country years imputed), and to a lesser extent wealth inequality measures, HNWI measures and population size (7, 4 and 3 country years imputed, respectively).


Furthermore, it was not possible to find the exact closing years for 25 private museums which were found to be no longer open.
#
These cases constitute a challenge for calcuating accurate density measures: 
#
Leaving out these museums entirely would lead to underestimated density estimates, while treating these museums as remaining open would overestimate private museum density as they were observed to be no longer open. 
#
Either method can substantially bias density estimates as in particular in countries with only a few private museums, a private museum more or less can have large impacts on per capita private museum rates.
# 
To be able to still use these cases in density estimates, closing year was imputed via linear regression based on the relationship between number of years opened and closing year of the museums for which both were available (n=53, R^2 = 0.68).
#
While imputed closing years are likely not always accurate, the resulting density estimates are likely more accurate than they would have been if closed museums had been excluded completely or treated as having remained open, especially given the high R^2 of imputation regression used for the traning data.


*** Data restrictions
#
A number of observations have been excluded for various reasons:
#
The exchange rates for Zimbabwe and Venezuela were deemed unrealistic (Venezuela is discussed by [[citet:&Blanchet_2017_conversions]]); both countries were therefore excluded.
#
The HNWI indicators for the United Arab Emirates, Saudi Arabia and Qatar display a strong decline between 2000 and 2010 of which both the starting value and the strength of the decline are extremely high (starting at several standard deviations above the mean and declining to average values) and hence likely caused by data issues; the countries are therefore excluded. 
#
Furthermore, a number of country-years have been removed for Yemen due to negative cultural spending.
#
For a number of years the wealth gini coefficient of South Africa was larger than 1; it has therefore been set to a ceiling of 0.95.
#
Finally, Iceland, the Bahamas, Monaco and Liechtenstein have been excluded as these countries' small population results in an extremely high rate of Artnews top 200 collectors per capita (and in the case of Iceland, also an extremely high rate of modern/contemporary art museums in 1990).
#
Since the number of Artnews collectors is a discrete count variable it is unable to provide accurate measures in countries with very small populations which justifies the exclusion of these countries on methodological grounds.



# #+latex: \begin{landscape}


# ** Descriptive statistics 
# :PROPERTIES:
# :ID:       9853457d-2c24-43bc-be97-28cafaa98a63
# :CUSTOM_ID: app_descs
# :END:


# #+INCLUDE: "./tables/tbl:descs_v27.tex" export latex
# #+latex: \end{landscape}




** Control Variables
:PROPERTIES:
:CREATED:  [2024-02-07 wo 17:51]
:ID:       b60f84ec-baff-4f09-bc01-10ae96d70d13
:CUSTOM_ID: app_controls
:END:

*** GDP :ignhead:

The coefficient of GDP per capita is generally positive. 
#
In the two larger datasets, it is significant and also substantially larger with values of {{{gdp_coef_cbn2}}} and {{{gdp_coef_cbn3}}} for "DS --CuSp" and "DS --CuSP/TMITR" respectively, compared to {{{gdp_coef_cbn1}}} for "DS all IVs".
#
# *which is substantial especially when considering that in datasets with more country years GDP per capita has a smaller standard deviation ({{{gdp_1SD_cbn2}}}, {{{gdp_1SD_cbn3}}} and {{{gdp_1SD_cbn1}}} in "DS -CuSp", "DS -CuSp/TMTIR and "DS all IVs", respectively).*
# not clear if this makes sense, maybe just cut -> just focus on smorc mediation/DS composition
# 
This between-dataset variation in coefficient size could indicate mediation of GDP through cultural spending (cf. appendix \ref{app_mediation} and figure {{{rplt_oucoefchng}}}); however further investigation would be required to more clearly determine the mechanism at play. 
# could link to {{{rplt_oucoefchng}}}, supports mediation
# FIXME add speculation about mechanism
Economic growth is also positive and significant in all data sets.


*** Density Dependence :ignhead:

In all datasets on the country level, and in all but "DS all IVs" on the global level, measures of density (legitimacy) and density squared (competition) correspond to the density-dependence paradigm, i.e. an inverted U-shaped relationship between density and private museum founding (indicated by the significant negative coefficient of the squared density measure on the country and global level). 
#
# The pattern of a negative coefficient of the squared density measure (which is significant everywhere except for the global coefficient in "DS all IVs"; where however it is marginally significant), is present for the density measures on the level of both the country and the world.
#
Private museum founding thus is generally compatible with the density dependence paradigm, according to which potential founders are motivated by their peers' decision to establish a private museum up to the point where private museum numbers increased to the extent that additional founding does not appear advantageous anymore.
#
However, density in neighboring countries does not fit this trend.
#
While the coefficients are insignificant in the two larger datasets, in DS all IVs it describes a U-shaped relationship, corresponding to higher rates of founding at the extreme ends of the scale.
#
Given the right-skewed distribution of neighbor density, increasing density in neighboring countries primarily decreases private museum founding in the focal country.
#
Furthermore, while prospective founders might ultimately be disincentivized by growing private museum numbers, there is no evidence for a demotivating effect of museum closures, as the coefficient of the cumulative number of museum closures is not significant.

# While the general pattern thus follows the density-dependence literature, the particular values of the coefficients indicate additional complexities.
# #
# Whereas in "DS all IVs" the maximum of the private museum country density curve is reached at a value of {{{dens_cry_top_point_std_cbn1}}}, correponding to a density of {{{dens_cry_top_point_cbn1}}} private museums per million inhabitants, which constitutes a value higher than observed in {{{dens_cry_top_below_CYs_prop}}}% of country years, the maxium of the global density curve is already reached at a value of {{{dens_glbl_top_point_std_cbn1}}}, corresponding to the global private museum count of {{{dens_glbl_top_point_cbn1}}}, which is a value only higher than {{{dens_glbl_top_below_CYs_prop}}}% of country years (and corresponds to the value reached in year XXXX).
# #
# In other words, the country-level capacity appears to be higher than the global carrying capacity, as on the country-level increasing private museum densities are associated with higher chances of private museum foundings for a substantially larger section of the data than on the global level.
# # this is 92% made up
# A possible reason for this phenomenon could be that unobserved variables limit the founding chances for a number of countries, as a consequence of which the country-level carrying capacity is disproportionally based on the countries in which foundings take place and therefore constitutes a level which can't be reached in most countries. 
# #
# However, more research is needed to investigate this phenomenon further. 


# density dependence also has large model improvement


# *** Art field indicators :ignhead:

# Similary, the coefficients of the art field indicators (the number of museums of modern and contemporary art and of the number of collectors in the Artnews top collector ranking) are relatively small and insignificant in all datasets.

# ***** intercept :ignhead:
# leave for now

# The intercepts describe the predicted founding rate for a hypothetical country with values of zero on all predictors, which given the standardizing corresponds to the mean values on all variables except the tax deductibility of donations, where zero instead corresponds to no tax deductibility of donations.
# #
# The 


*** Social Fragmentation
While the effects of ethnic fractionalization are not significant in all datasets, they are consistently negative, thus giving some support to the expectation that more fractionalized societies provide lower incentives for civic engagements and public good provision.
#
However, this is not the case for the effect of Migrant stock, which is only negative in "DS all IVs", but positive in the other two datasets.
#
Possible explanations for these findings might be the measurement of fragmentation on the country-level, whereas these mechanisms likely take place on a more local level, as well as a more complex relationship between fragmentation and pro-social behavior [[citep:&Baldassarri_Abascal_2020_diversity]].
#








** Coefficient Distribution
:PROPERTIES:
:ID:       f1b8a0fd-2efa-4034-b7bf-c17991fd340c
:CUSTOM_ID: app_coefdrbn
:END:


{{{ynkplt_coef_violin}}}

#+latex: \FloatBarrier


** Model improvement given inclusion of variables 
:PROPERTIES:
:ID:       ddb30663-9a58-4af5-977c-43f83903776c
:CUSTOM_ID: app_llrt
:END:


{{{ynkplt_oneout_llrt_lldiff}}}



{{{ynkplt_oneout_llrt_z}}}

To investigate whether a variable improves the model, a comparison is made between the full model and the full model without the variable in question.
# 
For each dataset there are 36 models (due to variables choices for HWNI (4 different thresholds) and inequality measures (1 of 3 for both wealth and income inequality)), resulting in 108 models in total. 
#
For each variable in each of these models a reduced model is constructed by removing the variable in question and comparing model fit to the full model.
#
# fuck actually doesn't really make sense to compare a full model with smorc_linear and squared to one iwth only linear
# also my improvement of smorc is weird: same for both smorc linear and smorc squared
#
If a variable has a squared term or interaction, it is removed together with the main term.
#
Furthermore additional reduced models is constructed, namely one without the four density variables (country and global density linear and squared), as well as one without the density variables and closings.
#
Given that the datasets differ in their number of variables, a different number of reduced models is calculated per dataset, in particular 834 for "DS all IVs", 792 for "DS --CuSp", and 720 for "DS --CuSp/TMITR". 
# 
The lags of the reduced models are not optimized due to computational limitations. 



Figure {{{rplt_oneout_llrt_lldiff}}} shows the distribution of differences in log-likelihood between the full and reduced models per variable and dataset.
#
Furthermore, a likelihood ratio test ($LR = 2[LL_{reduced} - LL_{full}]$) is conducted to compare each reduced to its corresponding full model.
#
The likelihood ratio statistic follows a Chi-square distribution; its corresponding p-value was converted to a z-score to facilitate interpretation.
#
The distribution of z-scores per variable and dataset is shown in figure {{{rplt_oneout_llrt_z}}}.
# 
Both analysis correspond in large parts to the results of the main regression analysis insofar as variables with significant coefficient correspond to significant and/or substantial model improvements.
#
# There are however a few exceptions, such as tax deductibility of donations in "DS -CuSp/TMITR", GDP per capita in "DS all IVs" as well as some inequality variables in "DS all IVs" in which a significant coefficient does not always correspond to a significant model improvement. 

#+latex: \FloatBarrier



** Influence of variable inclusion on regression coefficients
:PROPERTIES:
:ID:       887311dc-92a8-4b21-9f0e-0b0a6eeb38d5
:CUSTOM_ID: app_mediation
:END:


I furthermore analyze the coefficients of the restricted models to investigate potential mediation; results are presented in figure {{{rplt_oucoefchng}}}.
#
The variables (or variable sets of all density variables and all density variables plus closures) that are added are placed on the x-axis, the coefficients of the full model are placed on the y-axis;
# 
Each point shows the average difference between the coefficient of the full and the restricted model and can be understood as the effect that adding variable v_x to the model has on the coefficient of variable v_y.
#
For example, if GDP has a coefficient of 0.5 in the full model and one of 0.7 in a restricted model (e.g. one without cultural spending), the difference is 0.5 - 0.7 = -0.2; thus adding cultural spending to the model results in an decrease of the GDP coefficient by 0.2. 
#
Positive coefficient changes (i.e. a larger coefficients in the full model than in the restricted model) are colored as red, negative coefficient changes as blue; points are furthermore scaled by the absolute coefficient size to compare both positive and negative changes. 


A number of findings can be gleaned from this analysis.
#
Firstly, wealth and income inequality appear "mutually reinforcing".
#
The inclusion of income inequality increases the coefficients of wealth inequality (which is positive in the full model) and the inclusion of wealth inequality decreases further the negative coefficient of income inequality (which in the full model is negative).
#
This unexpected pattern (as well as the divergent inequality in general) clearly calls for further research to disentangle relations of inequality.


Secondly, a number of variables appear to partly mediate GDP.
#
The coefficient of GDP decreases as other variables are added, which indicates that part of the effect is mediated through these variables.
#
This in particular concerns the effects of density, tax incentives and cultural spending, and to a lesser extent the effect some HNWI measures for "DS all IVs".
#
Conversly, adding GDP to a model in which it was not included before reduces the coefficients of HNWIs and museums of modern/contemporary art.


Finally, there are a number of substantial coefficient changes given inclusion which do not offer a straightforward explanation, such as decreases of the coefficient of modern and contemporary art museums when including income inequality measures, increases of the linear density term when adding wealth inequality variables, increases of income inequality coefficients when adding density measures, as well as changes to the intercept in both directions when adding different variables. 
#
Exploring the various cases of potential mediation (or other forms of variable relations) is beyond the scope of the paper, but constitutes a promising start for future research.



*** Insignifiance of HNWI effects

Next to the substantial argument for the insignifiance of elite wealth effects proposed in the main text, namely a theoretical expectation based on selection bias, a more technical possibility is that HNWI effects might be controlled away by other variables that also measure HWNI rates, such as GDP per capita, Artnews collector rates, wealth inequality or private museum density.
#
The evidence for this is strongest in the case of GDP, as its addition shrinks HNWI coefficients in the two larger datasets (figure {{{rplt_oucoefchng}}}).
#
However since in the full model the HNWI coefficients are predominantly negative the addition of GDP does not reduce the strength of the association from substantial to negative, but rather from unsubstantial to negative and (marginally) significant. 
#
Furthermore, little evidence of HNWI coefficient change exists following the addition of wealth inequality and Artnews collectors, and even less for private museum density the addition of which actually marginally increases the HNWI coefficients.
#
As the models which form the basis for figure {{{rplt_oucoefchng}}} exclude only one variable at a time, it cannot be ruled out completely that a different specification without any variables that might also capture the elite wealth mechanism might result in substantial main HWNI effects.
#
However, the overall relative small size of coefficient changes by single variable exclusion does not provide strong evidence for overcontrolling as the explanation of insignificant HNWI effects. 


#+latex: \begin{landscape}

{{{ynkplt_oucoefchng}}}

#+latex: \end{landscape}




** Lag Choice
:PROPERTIES:
:ID:       68b9f836-26ed-4340-899f-4d6c31192cd5
:CUSTOM_ID: app_lagchoice
:END:


{{{ynkplt_lag_dens}}}

Figure {{{rplt_lag_dens}}} shows the distribution of the lag of the coefficient after optimization.
#
As often time lags different from one year are chosen (which would likely constitute the default if they were not varied), it can be seen that allowing the lag to vary substantially increases model fit. 
#
It furthermore seems to be the case that the HNWI coefficients (which are not significant) vary the most in regards to their lag choice (which is plausible since a non-substantial overall effect could imply that the particular lag does not matter much). 
# , which is plausible insofar as a flat 




** Multicollinearity 
:PROPERTIES:
:ID:       ea69b444-c363-4714-a010-3e529c8479e7
:CUSTOM_ID: app_vif
:END:

{{{ynkplt_vif}}}


VIFs were calculated for the best-fitting model of each variable set and dataset (108 models in total given 1 of 4 HWNI variables \times 1 of 3 income inequality variables \times 1 of 3 wealth inequality variables \times 1 of 3 datasets) using the R =performance= package [[citep:&Luedecke_etal_2021_performance]]. 
# 
As squared variables and interactions can result in high VIFs without substantial collinearity, I calculate VIFs once for the full model and once after excluding squared variables and interactions.
# 
Figure {{{rplt_vif}}} shows the distribution of the variance inflation factors.
#
While VIFs can be substantial when including squared variables and interactions, no multicollinearity issues are present when focusing only on the linear variables (all VIFs < 10, all VIFs except global density (which after removing squared variables is still based on the same data as global density) and GDP per capita in "DS all IVs" < 5).
#



** Longitudinal development
:PROPERTIES:
:ID:       0bbb364a-078f-4f4c-a409-4a18564eba99
:CUSTOM_ID: app_velp
:END:


The within-country changes were analyzed to characterize the development of the longitudinal variables over the observation period.
#
In particular, for each variable a separate regression model was run which regresses the variable in question at lag 0 against year while allowing slopes and intercepts to vary by country (year is set to 0 in 1995, the beginning of the observation period).
#
# *can only cover linear country trends, especially since changes are usually reported as percentage change*
#
Results are presented in figure {{{rplt_velp}}}.
#
The histogram shows the distribution of country slopes, while the dot and whiskper shows the overall slope estimate with a 95% confidence interval.
#
For example the overall slope of top marginal income tax rates is {{{velp_mean_uscld}}} (indicating an average yearly decrease of top marginal income tax rates by {{{velp_mean_scld}}} percentage points), however the histogram shows that countries can substantially diverge from this overall slope: 
#
Slopes of countries (with at least 20 years of data) can range from a minimum of {{{velp_year_scld_min}}} (a yearly decrease by {{{velp_year_pct_min}}} percentage points in the case of {{{velp_cryname_min}}}) to a maximum of {{{velp_year_scld_max}}} (a yearly increase of {{{velp_year_pct_max}}} percentage points in the case of {{{velp_cryname_max}}}), with 25% and 75% slope quantiles corresponding to {{{velp_quantl25_uscld}}} (-{{{velp_quantl25_scld}}}%) and {{{velp_quantl75_uscld}}} ({{{velp_quantl75_scld}}}%), respectively.
#
Furthermore, the correlation between slope and intercept is included:
#
A positive correlation indicates that countries with higher constants (i.e. predicted value in 1995) achieve higher growth over the observation period than countries with lower constants (thereby "extending their lead"), whereas negative correlations indicate that countries with lower constants experience higher growth (thereby "catching up").


# main findings:
# - to the extent to which histograms of same variable are different between combinations, countries are not missing at random -> less biased estimates
# - TI decrease
# - smorc increase
# - inequalities show much variation, depending on dataset
# - hwni increase, but very unequally, many 0s
#   not artifact of construction: many 0 slopes also for low thresholds where there are almost no zeroes
  
A number of findings can be gleaned from this analysis.
#
First, country slopes can diverge substantially from the overall mean development on all variables, which should serve as a reminder to be cautious of treating global developments as homogenous between countries. 
#
This also further supports the methodological choice of using country-year as the unit of analysis instead of treating private museums as a homogenous global development; which could be further refined in the future by integrating random slopes into the main regression analysis.
#
Secondly it can be seen that top marginal income tax rates have on average been declining, while cultural spending as actually increased in most countries, which questions the characterization of government expenditure reduction but only to some degree as these characterizations focus primarily on countries with higher cultural spending, where due to the negative correlation between intercept and slope cultural spending has indeed decreased.
#
Thus the value of using a large number of countries rather than case studies which allows to characterize wider developments becomes especially clear.
#
Third, inequality measures as well show a wide range of developments.
#
While some average non-zero slopes are found (such as a an overall reduction of income inequality in DS -CuSp/TMITR and and increase in wealth inequality in DS all IVs), the variation even in these cases is still considerable. 
#
Fourth, HNWI indicators develop almost never negatively, although most countries see comparatively little growth (this is not a measurement artifact of assigning zero when no quantile is above the HNWI threshold in question as it occurs also at the lowest of 1M, where most country-years have non-zero values).
#
Furthermore average increases appear to be driven by a comparatively small number of countries with relatively large increases. 
#
Finally, GPD and private museum density see similar patterns of almost no decline with growth being concentrated in a handful of countries, while art collector rates are highly centered around zero, indicating stability (at zero art collectors) for most countries. 




#+latex: \begin{landscape}

{{{ynkplt_velp}}}

#+latex: \end{landscape}


# #+Latex: \begin{sloppypar}
# #+Latex: \printbibliography[segment=\therefsegment]
# #+Latex: \end{sloppypar}

#+LATEX: \bibliographystyle{plainnat}
#+LATEX: \bibliography{sup_materials.bib}









